### PR TITLE
Adding images for hillbert curve and marching squares

### PR DESCRIPTION
**Pull request by kfahn22**
Cont. 13 in marching squares is not loading for me.  

Deleting two showcases that  are no longer available.

### CODE REVIEW

**Comment by fturmel** [comment]
re: Cont. 13 in marching squares

These `ddns.net` urls are commonly used to self-host on a dynamic IP, so it's very likely that this link will remain dead.

I searched for "Metaballs" in the user's GitHub though and did find the source code if we want to link to that instead: https://github.com/YushchenkoAndrew/template/tree/master/JS/Metaballs

**Comment by fturmel** [comment]
The same user had another contribution hosted on the same domain if you want to change both at once: `content/videos/challenges/113-4d-hypercube-aka-tesseract/showcase/contribution6.json`

**Comment by kfahn22** [comment]
Thanks I updated the links.  It is a shame his website is no longer available.

**Comment by shiffman** [comment]
Thank you @kfahn22!

**Pull request merged**
