### PR TITLE
Demonstration of Showcase Submission

### PR DESCRIPTION
**Pull request by shiffman**
Showing how to add a showcase submission!

### CODE REVIEW

**Comment by shiffman** [comment]
There seems to an issue with requiring `npm run clean` when showcase submissions are added. This preview for this pull request does not show the submission:

https://deploy-preview-154--codingtrain-preview.netlify.app/challenge/167-prime-spiral

Screen Shot 2022-06-04 at 4 19 44 PM

When host the branch locally on my laptop, the submission shows up after I run `npm run clean`:

Screen Shot 2022-06-04 at 4 20 20 PM

Any idea why this might be happening? @runemadsen Do you know if there is a netlify setting I can change to force `npm run clean`?

In theory, there maybe is not problem if the showcase project shows up upon merge but it would be really nice to be able to double-check a preview before merging!

**Comment by shiffman** [comment]
Quick update, I tried this option—"Clear Cache and Retry Deploy"—on netlify and now it shows up! Seems like an extra unnecessary step, is there a way to force it to clear!?

Screen Shot 2022-06-04 at 4 23 05 PM

**Comment by fdoflorenzano** [comment]
> Quick update, I tried this option—"Clear Cache and Retry Deploy"—on netlify and now it shows up! Seems like an extra unnecessary step, is there a way to force it to clear!?

How about setting `npm run clean && npm run build` in Netlify's site settings (Build and deploy)?

**Comment by shiffman** [comment]
> How about setting npm run clean && npm run build in Netlify's site settings (Build and deploy)?

Ok, I'm trying this!

**Pull request closed without merging**
