### PR TITLE
Page CTA - More Customisations

### PR DESCRIPTION
**Pull request by dipamsen**
Allows to customise character, and variant of the CTA sections of every page:

image

image

image

image

(Changed showcase page cta color and character)

### CODE REVIEW

**Comment by shiffman** [comment]
@jasontheillustrator any thoughts on these?

**Comment by dipamsen** [comment]
I am unable to fix the error atm, if this is required right now, someone can push the fix - the fix is to either set Character={some character} in <PagePanel> in components.js, or set default value for the prop in Page Panel itself.

(I can probably do it myself within a few hours)

**Comment by fturmel** [comment]
I can handle it, give me a few minutes

**Comment by shiffman** [comment]
Amazing, thank you @fturmel and @dipamsen!

**Comment by jasontheillustrator** [comment]
> @jasontheillustrator any thoughts on these?

these look good to me.

**Pull request merged**
