### PR TITLE
Adding 136-perlin-noise-gif-loops

### PR DESCRIPTION
**Pull request by borntofrappe**
First attempt at porting a multi-part coding challenge. A few thing worth mentioning:

- the folder is labeled `136-polar-noise-loops` to match the name chosen in the Coding-Challenges directory, which stores the two parts as `136_Polar_Noise_Loop_1` and `136_Polar_Noise_Loop_2`
- the `groupLinks` field unites the references and videos from both challenges
- the images for the code examples are taken directly from the p5.js web editor
- `index.jpg` modifies the final example to add a purple background per the Coding Train color palette; for the particles I wasn't able to use a color from the same set, since the `r` and `b` component are computed from the noise value. All I did is increase the green component to create enough contrast

I did my best to add timestamps, but especially the second part was difficult to summarize. I'm opened to suggestions and improvements

### CODE REVIEW

**Comment by borntofrappe** [comment]
I realize only now the title in `index.json` is _Polar Noise Loops_... should I rename the project folder to add the plural version?

Apologies for the mixup (I'm positive is not the only one)

**Comment by kfahn22** [comment]
Thank you so much for this.  You did a great job!

One thing that is probably not clear from the guide is that the any linked videos that are challenges that have ALREADY been added to the website can be added as additionally to the relatedChallenge field.  They can be kept in the videos field as well, but that is not mandatory.

"relatedChallenges": ["36-blobby", "130-drawing-with-fourier-tranform-and-epicycles", "134-heart-curve", "135-making-a-gif-loop-in-processing"],

Another change that can be made is that the links for the challenges (again the ones that are ALREADY on website) can be relative, ie.  
"/challenges/36-blobby"

**Comment by kfahn22** [comment]
I am not sure this is better than your image, which I really like!  Just providing it to let you know that it is ok to edit the code a little bit when creating these images.   (I have edited the code to use the polar noise to vary alpha instead of the r and b values.)
polar

**Comment by borntofrappe** [comment]
Understood @kfahn22, thank you for the pointers

**Comment by kfahn22** [comment]
Thank you for all of your effort! It is truly appreciated!!

**Review by kfahn22 — APPROVED** [review]
This is great!

**Comment by shiffman** [comment]
Yay!! Great work @borntofrappe and thank you @kfahn22!

**Pull request merged**
