### PR TITLE
Ported CC 119 Binary to Decimal Conversion

### PR DESCRIPTION
**Pull request by DenisovichDev**
Added challenge binary to decimal conversion. Please check if you are okay with the `index.png` and the thumbnail.

### CODE REVIEW

**Comment by DenisovichDev** [comment]
@shiffman Can I have some help? :')
I had no issue with the dev build, I don't know why the netlify build failed. It's such a small PR too...

**Comment by DenisovichDev** [comment]
I know the checks have all failed, I need to know if this is my fault or there is an issue with the netlify build. Thank you.

**Comment by shiffman** [comment]
Hey! There are some errors that aren't yours. Can you merge main back into your branch? 

(If anyone knows I can do this myself, I'd love to know! I'm having trouble figuring out how to do so for a forked branch.)

**Comment by shiffman** [comment]
Oh I see you actually just did that, let me fix one or two more things, please hold!

**Comment by shiffman** [comment]
This should work now! I'm going to go into netlify and clear cache and manually trigger a rebuild, this sometimes does the trick!

**Comment by DenisovichDev** [comment]
Thanks! I hope this works

**Comment by shiffman** [comment]
I can confirm that this builds without any errors locally! @DenisovichDev apologies there is an issue on Netlify's side. I'm trying a few things, if I can't get the preview to deploy properly I will merge regardless soon!

**Comment by DenisovichDev** [comment]
No need for apologies! I just wanted an assurance that I wasn't doing anything wrong so that I can continue porting

**Comment by shiffman** [comment]
@DenisovichDev I submitted a support ticket to Netlify to see if they can help resolve this. I'm perfectly happy to just merge it (as I know it builds and runs locally no problem) but am hoping we can resolve the issue so that it doesn't happen again in the future. If you want to merge it with main again feel free! Maybe we should also revert this last https://github.com/CodingTrain/thecodingtrain.com/pull/291/commits/8d07ef119b4e8a25f9aa3b3c23f83371872d70ce where I was just messing around?

**Comment by DenisovichDev** [comment]
Hey @shiffman! Thanks for the help, I agree with you, this PR can wait until the problem is resolved. No need to merge right now. I'll revert it back to 63406d723e1242229bcab449d8a18fea0bb1587a then!

**Comment by DenisovichDev** [comment]
Looking good so far this time!

**Comment by shiffman** [comment]
Well, I'm merging this before anything else happens!! 😂

**Comment by DenisovichDev** [comment]
@shiffman Haha! Well that was a trip.

**Pull request merged**
