### PR TITLE
Showcase Submission for code/2-variables/4-random

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Mohammed Ayath (aka GD Cyber) for your contribution! A member of the Coding Train team will review it shortly.

* [Guys help my project is tweaking](https://editor.p5js.org/gdcyber0303/full/LSprpvbtH)
* Mohammed Ayath (aka GD Cyber)

preview image

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @GDCybernetix, thank you for submitting! It's my preference that the thumbnail images are screenshots of the sketches themselves. Would you mind if I swapped out the image for a screenshot of your sketch? Great job coding!

**Comment by kfahn22** [comment]
I have replaced with an image from the sketch.

**Comment by shiffman** [comment]
Thank you @kfahn22!

**Comment by GD-Cybernetix** [comment]
yeah i just realized im on here and uh i kinda quit p5 so uh

**Comment by kfahn22** [comment]
I am unsure based on your comment, do wish to have your showcase removed from the website?

**Pull request merged**
