### PR TITLE
Adding 131-bouncing-DVD-logo

### PR DESCRIPTION
**Pull request by borntofrappe**
Adds challenge 131.

A note to make on the demo proposed in the p5 web editor: https://editor.p5js.org/codingtrain/sketches/Ya1K1ngtFk

If you run the code all you see is the string 'Loading..' and the console prompts a 404 error. It seems the image is no longer available, and you might need to re-upload the asset. 

If you need a copy the repository devoted to the coding challenge has a `.png` version: https://github.com/CodingTrain/Coding-Challenges/blob/main/131_BouncingDVDLogo/P5/dvd_logo.png

### CODE REVIEW

**Comment by kfahn22** [comment]
Thank you, this looks great!!  Here is a link to a sketch that has been updated.

https://editor.p5js.org/codingtrain/sketches/S-es-dYVn

**Comment by borntofrappe** [comment]
Thanks for the assist. Personally I find the logo moves a tad too fast, but I'll leave the choice to you :) 

You may want different values for the horizontal and vertical speed though 👍

**Comment by borntofrappe** [comment]
I updated the image for the demo as well. I wasn't particularly proud of the first one, which I created manually and by coloring the logo in GIMP.

**Comment by shiffman** [comment]
Looks great! Yay!

**Pull request merged**
