### PR TITLE
Showcase Submission for noc/perlin/graphing-1d-perlin-noise

### PR DESCRIPTION
**Pull request by ferreira-mariana**
Hi!

In this PR 
- I've added a showcase for the video "Graphing 1d Perlin Noise" from the Nature of Code track. When @shiffman said 'wandering bee buzzing behavior' on 2:55, I remembered the song [Flight of the bumblebee](https://www.youtube.com/watch?v=aYAJopwEYv8). I immediately paused the video and started doing this [animation](https://editor.p5js.org/ferreira-mariana/full/Yk699UUQZ) of a bee flying with this song on the background, fits very well with the behavior of perlin noise! 
- I've also fixed the name of my last contribution (which I submitted via the submission form) so that it follows the project name pattern.

Happy to contribute :)

### CODE REVIEW

**Comment by dipamsen** [comment]
Thanks for submitting! By the way, you do not need to rename the auto generated files, as by convention, they are named automatically with a timestamp (which acts as a unique id), whereas manual submissions via PRs are numbered as `contributionN.json`.

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by ferreira-mariana** [comment]
oh nice, I didnt know that, thanks for the explanation!!
I just reverted that change then

**Comment by shiffman** [comment]
Amazing, this is bee-autiful!! Thank you sharing @ferreira-mariana!!

**Pull request merged**
