### PR TITLE
Adding 111-animated-sprites

### PR DESCRIPTION
**Pull request by borntofrappe**
Following the example of #103 I've tried to summarize the changes in a fewer commits.

- [x] updated contributions to replace missing pages and add images
- [x] updated index.json with the topics, links, and image for the challenge, icons and descriptions for links

### CODE REVIEW

**Comment by dipamsen** [comment]
Thanks again for all the help with porting! Here are some minor points (not really important):
1. The `[codeExamples].urls.other` property is not really necessary for p5 and processing challenges, since both of those have a separate field, and the p5 code can be already accessed from the web editor. The `other` property is for anything which is not p5 or processing, or a standalone GitHub repo.
2. The `source` property in the showcase contributions is deprecated, so it can be removed. ([contribution template](https://github.com/CodingTrain/thecodingtrain.com/blob/main/content/templates/showcase/contribution1.json))

**Comment by kfahn22** [comment]
Thank you, this looks great!

**Review by kfahn22 — APPROVED** [review]
This looks great!

**Comment by borntofrappe** [comment]
Followed your guidance @dipamsen. Thanks for the tips and the contribution's template.

**Comment by kfahn22** [comment]
Thank you for your attention to detail!

**Comment by shiffman** [comment]
@borntofrappe I think we can use [this image](https://github.com/CodingTrain/thecodingtrain.com/pull/640/files#diff-e4554dbf8c87fc0b66c3ed0ee88473cdc2e0f38b5bf48989893819bbd81804e9) for the `index.jpg` as well! Let me know if you want to change it or prefer we take care of it after merging!

**Comment by borntofrappe** [comment]
Seems like a solid choice. Is there a specific size or aspect ratio for the thumbnail? If not I can go ahead and replace the current `index.jpg` 👍

**Comment by dipamsen** [comment]
@borntofrappe I believe the standard aspect ratio for the thumbnails is 16:9, but the current image (4:3) also works, the image is automatically cropped and resized in the site.

**Comment by borntofrappe** [comment]
@dipamsen great, I'll go ahead with the current image then

**Comment by kfahn22** [comment]
Now that the sprite image is being used as the index image, the  animated-sprites.jpg image and reference in the json file can be deleted.  When no code images are provided, the index image is used by default as the code example image.  Would you like to take care of this, or I can update.

**Comment by borntofrappe** [comment]
I'll take care of it promptly @kfahn22

**Comment by shiffman** [comment]
Wonderful work, wow!

**Pull request merged**
