### PR TITLE
Replace video/playlist links to relative website urls instead of Youtube links

### PR DESCRIPTION
**Pull request by dipamsen**
Wrote a script to update Coding Train youtube links in the metadata into website links (if that video is present on the website).

### CODE REVIEW

**Comment by dipamsen** [comment]
Some questions regarding this: (@shiffman)

- Pendulum Simulation: https://www.youtube.com/watch?v=9iaEqGOh5WM
  - Should this be updated to https://thecodingtrain.com/tracks/the-nature-of-code-2/159-simple-pendulum
  - linked from [Double Pendulum](https://github.com/CodingTrain/thecodingtrain.com/blob/1e854c3e43db2ba47b432f8fb99c5a8dae57d9cc/content/videos/challenges/93-double-pendulum/index.json#L70)

- Pixels!: https://www.youtube.com/watch?v=EmtU0eloTlE
  - Should this be updated to : https://thecodingtrain.com/tracks/p5-tips-and-tricks/more-p5/pixel-array
  - linked from [Photo Mosaic](https://github.com/dipamsen/thecodingtrain.com/blob/1e854c3e43db2ba47b432f8fb99c5a8dae57d9cc/content/videos/challenges/49-photo-mosaic-with-white-house-social-media-images/index.json#L93-L94), [Langton's Ant](https://github.com/dipamsen/thecodingtrain.com/blob/1e854c3e43db2ba47b432f8fb99c5a8dae57d9cc/content/videos/challenges/89-langtons-ant/index.json#L52-L53), [Dithering](https://github.com/dipamsen/thecodingtrain.com/blob/1e854c3e43db2ba47b432f8fb99c5a8dae57d9cc/content/videos/challenges/90-dithering/index.json#L81-L82)

- Deleting objects with splice: https://www.youtube.com/watch?v=HXOD_XDA-KU
  - Should this be updated to : https://thecodingtrain.com/tracks/code-programming-with-p5-js/code/7-arrays/5-removing-elements
  - linked from [Evolutionary Steering Behaviors](https://github.com/dipamsen/thecodingtrain.com/blob/1e854c3e43db2ba47b432f8fb99c5a8dae57d9cc/content/videos/challenges/69-evolutionary-steering-behaviors/index.json#L163-L164)

- Trigonometry and Polar Coordinates: https://youtu.be/znOBmOrtz_M
  - Should this be updated to : https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/3-angles/4-polar-coordinates
  - linked from: [Butterfly Generator](https://github.com/dipamsen/thecodingtrain.com/blob/1e854c3e43db2ba47b432f8fb99c5a8dae57d9cc/content/videos/challenges/60-butterfly-generator/index.json#L82-L83)

- ml5.js: Sound Classification: https://www.youtube.com/watch?v=cO4UP2dX944&list=PLRqwX-V7Uu6YPSwT06y_AEYTqIwbeam3y&index=19
  - This video is not on the website. Is this intentional?
  - linked from: [Chrome Dino Game](https://github.com/dipamsen/thecodingtrain.com/blob/1e854c3e43db2ba47b432f8fb99c5a8dae57d9cc/content/videos/challenges/147-chrome-dinosaur-game/index.json#L64-L65)

- Angles and Angular Motion: https://youtu.be/qMq-zd6hguc
  - Should this be updated to: https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/3-angles/1-angles-and-rotation
  - linked from: [LOGO interpreter](https://github.com/dipamsen/thecodingtrain.com/blob/1e854c3e43db2ba47b432f8fb99c5a8dae57d9cc/content/videos/challenges/121-logo-interpreter/index.json#L117-L118)

**Comment by fturmel** [comment]
Very cool!

**Comment by shiffman** [comment]
Amazing!

**Comment by dipamsen** [comment]
@shiffman any preference/suggestions for the above questions? https://github.com/CodingTrain/thecodingtrain.com/pull/1097#issuecomment-1575072094

**Comment by shiffman** [comment]
> @shiffman any preference/suggestions for the above questions? [#1097 (comment)](https://github.com/CodingTrain/thecodingtrain.com/pull/1097#issuecomment-1575072094)

Oh, sorry I missed those!

I think the answer is yes for linking to the most recent / relevant video on the topic!

Regarding the sound classification video, I think that's just a mistake I can't remember any reason it would not be included!

**Comment by kfahn22** [comment]
The sound classification video wasn't in the playlist on the old website and I used that as a guide for what to add.  Should I add it now?  I also think we could add the ml coding challenges to the track as well, correct?

**Comment by shiffman** [comment]
Merging this, thank you for working on it @dipamsen it's amazing!

**Pull request merged**
