### PR TITLE
Add script to generate YT descriptions

### PR DESCRIPTION
**Pull request by dipamsen**
- [x] CLI - allow single video
- [ ] Work with `playlistId` field in tracks

*****

### Usage:

```shell
npm run yt-desc [path/to/index.json] # path must not start with `content/videos`
```
Examples: 
- `npm run yt-desc`
- `npm run yt-desc noc/2-forces/4-drag-force`
- `npm run yt-desc challenges/52-random-walker`

The generated `txt` files are saved in `_descriptions`.

*****

- The script parses each and every track file **and** video file, even to generate just one description. This is done to get other information, such as:
  - Playlist URL
  - Previous/Next Video
  - YT Links to other videos which have relative URLs

### CODE REVIEW

**Comment by shiffman** [comment]
@dipamsen sorry i messed something up merging with main to use this script for the WFC video. It worked great!

Noting I would like to add the following to the template:

```
Editing by Mathieu Blanchette
Animations by Jason Heglund
Music from Epidemic Sound
```

**Comment by dipamsen** [comment]
@shiffman added it and marked ready to review in case you want to merge!

**Comment by shiffman** [comment]
Hey! So the new website has more generic categories for groups of links than the old system which only had "links" and "videos". See the WFC page for how a video with a lot of different kinds of references can be organized! So I think something like the following that generates a block of links for each group would make more sense for this script:

```javascript
  for (let group of data.groupLinks) {
    description += `\n${group.title}:\n`;
    for (const link of group.links) {
      const url = link.url;
      if (/https?:\/\/.*/.test(url)) {
        // Starts with http:// or https://
        description += `${link.icon} ${link.title}: ${url}\n`;
      } else {
        // assume relative link in thecodingtrain.com
        description += `${link.icon} ${link.title}: https://thecodingtrain.com${url}\n`;
      }
    }
  }
```

Let me know what you think! I can make this adjustment directly but wanted to check with you first!

**Comment by dipamsen** [comment]
That looks amazing! Added this, and also added some fallback default emojis to support old videos which might not have emojis.

**Comment by shiffman** [comment]
Wow! I think it's time to merge this and then we can make further updates or changes as needed! I'm not sure why the checks are failing though, any ideas? The tests pass running this branch locally, here's what the Netlify logs say, but I can't make sense of it. I'll try "clear cache and retry" again.

Screen Shot 2022-07-04 at 10 46 40 AM

**Comment by dipamsen** [comment]
I have no clue about the error, but it is not specific to this PR as the same error is on #291 which is just a normal coding challenge porting.

**Comment by dipamsen** [comment]
Seems like the checks are passing now 🎉

**Comment by shiffman** [comment]
Going to merge this now so we have it to use in main! We can open new issues and make updates as necessary later, thank you!

**Pull request merged**
