### PR TITLE
Added my showcase for Bubble Sort!

### PR DESCRIPTION
**Pull request by AyushKoul00**
This contains my submission for Bubble Sort Visualization!

### CODE REVIEW

**Comment by shiffman** [comment]
Does this look like it will work now?

**Comment by DenisovichDev** [comment]
@AyushKoul00 has it been recognised this time?

**Comment by AyushKoul00** [comment]
Yes it is showing the PR but currently it says "not accepted" since it hasn't been merged yet

**Comment by shiffman** [comment]
Let's try merging!

**Pull request merged**
