### PR TITLE
Add Sound track

### PR DESCRIPTION
**Pull request by kfahn22**
I haven't been able to find the code examples.  If you can let me know where they are I can add (or I can recreate).

Notes: 
- I added an additional  link to Jason Segal's therewasaguy/p5-music-viz repo - lots of useful stuff there but can delete.
- I couldn't find the repo with sound file used in 5-adding sound effects. ( I added a link to https://opengameart.org as an alternative.)

### CODE REVIEW

**Comment by dipamsen** [comment]
@kfahn22 is this what you're looking for?
https://github.com/CodingTrain/website-archive/tree/main/Tutorials/P5JS/p5.js_sound

**Comment by kfahn22** [comment]
The sound file for "Just Like a Rainbow" is 7MB so I don't think I can or should upload it to the code example sketches, correct?  I am providing a link to the repo where it can be found, but I am wondering whether I should add a smaller sound file?  For example, I am using this one in a sound visualization I created (it is 542KB).  https://opengameart.org/content/sea-star

**Comment by kfahn22** [comment]
I just checked and the file size limit is 5MB.  I will just include this.dot.

**Comment by shiffman** [comment]
@kfahn22 I'm fine with using any sound file as long as the license allows it! I'll go ahead and merge and if you want to DM me I can dig up the original track or we can pick whatever you prefer!

**Pull request merged**
