### PR TITLE
Showcase Submission for 178-climate-spiral

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Luka Negoita for your contribution! A member of the Coding Train team will review it shortly.

* [Swimbot creature chatbot with node.js server! (didn't know which challenge to select)](https://github.com/LukaNeg/swimbot-chatbot)
* [Luka Negoita](https://lukaneg.github.io/)

preview image

### CODE REVIEW

**Comment by dipamsen** [comment]
Hey @LukaNeg ! Thanks for your submission!
Do you think your submission fits in with one of these videos?
- [Voice Chatbot with p5.Speech](https://thecodingtrain.com/challenges/80-voice-chatbot-with-p5speech)
- [Number Guessing Chatbot](https://thecodingtrain.com/challenges/79-number-guessing-chatbot)

**Comment by LukaNeg** [comment]
> Hey @LukaNeg ! Thanks for your submission! Do you think your submission fits in with one of these videos?
> 
> * [Voice Chatbot with p5.Speech](https://thecodingtrain.com/challenges/80-voice-chatbot-with-p5speech)
> * [Number Guessing Chatbot](https://thecodingtrain.com/challenges/79-number-guessing-chatbot)

Hi @dipamsen! Thanks for following up. I went through the "Working with data and APIs in Javascript" learning track, and the final video in that track was [Web Application Deployment](https://thecodingtrain.com/tracks/data-and-apis-in-javascript/data/3-the-weather-here/5-web-application-deployment). Here's a screenshot of the page and passenger showcase where I thought I'd add the webpage I made: 
image

I know it's not the Weather App, but I used at least 90% of what I learned through this track to build and deploy a node.js app, which ended up being a custom GPT chatbot. Could not have built this with these videos.

@shiffman on a side note, I'm guessing you already have this in your plans, but it would be amazing if you could share a tutorial on how to build an app with OpenAI's APIs. I was successful in this case (all due to your awesome Data and API's in Javascript track), but I know that I could do better on how I specifically set up and used OpenAI's APIs in my app for the chatbot I made. For example, I only got it to work with sending one POST request, but I'd love to learn how to send more than one by creating more than one api connection if that makes sense. 

Thanks again!!!! After skimming through tons of online tutorials, this was really the creme de le creme and I feel super empowered now. And this is coming from a data scientist with more than 10 years of professional experience.

**Comment by shiffman** [comment]
Adding it to the Data and APIs track makes sense to me! Our system is a little wonky but for a project made from the overall concepts from the track I agree the best place for it is probably the last video (where you can see other projects).

@LukaNeg I am hoping to do some videos about working with the OpenAI API, I am planning to teach about it in my fall NYU course. I'm a little conflicted b/c I generally prefer not to use commercial, closed systems in my videos so might look at some more open source alternatives hosted on HuggingFace. Still figuring out the best approach!

Also, thank you for the GitHub sponsorship! If you join the Coding Train discord, tag me so that I can add you to the member channels!

**Comment by LukaNeg** [comment]
> @LukaNeg I am hoping to do some videos about working with the OpenAI API, I am planning to teach about it in my fall NYU course. I'm a little conflicted b/c I generally prefer not to use commercial, closed systems in my videos so might look at some more open source alternatives hosted on HuggingFace. Still figuring out the best approach!

That makes sense, thanks! And yes, I'd also love to learn more about the open-source alternatives. For example, I started playing around with trying to get Dolly to work, but I think I might have a GPU problem there haha. I'm sure you'd have the solution, so I'm looking forward to that. :)

**Comment by shiffman** [comment]
@LukaNeg would you like to resubmit or move the files or shall we take care of it on our end?

**Comment by fturmel** [comment]
I moved the contribution files to the [Data and APIs track](https://deploy-preview-1028--codingtrain.netlify.app/tracks/data-and-apis-in-javascript/data/3-the-weather-here/5-web-application-deployment), should be good to merge!

**Comment by shiffman** [comment]
You are a hero @fturmel!

**Pull request merged**
