### PR TITLE
Challenge 73 - Acrostic

### PR DESCRIPTION
**Pull request by fturmel**
Related #1627

https://deploy-preview-1671--codingtrain.netlify.app/challenges/73-acrostic

Created chapters for the video and migrated content from
https://github.com/CodingTrain/website-archive/blob/main/_CodingChallenges/073-acrostic.md?plain=1

Some notes:
- http://shiffman.net/a2z/ is not working anymore, so I replaced it with the A2Z GitHub org instead
- ~~I linked the source code from the archived website.~~ It is however not working, the Wordnik words search API endpoint has been deprecated.
CleanShot 2024-07-20 at 11 34 53@2x

**TODO**

 - [x] Add thumbnail image
 - [x] Finalize the updated sketch using Datamuse (?)
 - [ ] Update video description on YouTube to fix missing chapters and dead links?

### CODE REVIEW

**Comment by dipamsen** [comment]
Code example can be linked from https://github.com/CodingTrain/Coding-Challenges

**Comment by fturmel** [comment]
> Code example can be linked from https://github.com/CodingTrain/Coding-Challenges instead of the archived repo

Thanks, much better.

**Comment by shiffman** [comment]
FYI the shiffman.net website is archived here! https://shiffman-archive.netlify.app/a2z/

I'm not maintaining it so I moved it off of shiffman.net (which now forwards to thecodingtrain.com) but I'm happy to link to any old but still useful material.

I prefer to recreate the code examples from the videos as p5 web editor examples (if they don't require node.js). I have some working wordnik examples as part of my last fall class's materials: https://editor.p5js.org/a2zitp/collections/cgfJWhpsE Maybe I could update the code?

**Comment by kfahn22** [comment]
Since v4 has been deprecated (at least until v5 is released), we will need to substitute a different endpoint.  (The code examples from the fall no longer return results.). ChatGPT suggested Datamuse as a  substitute.  Here is a sketch using it, although the code is slightly different -- the return options are more limited. The sketch creates the index.jpg file so if used the extra css will need to be edited.   If this is OK I can edit it and create a code example.  

https://editor.p5js.org/kfahn/sketches/1-UXfIl9b

index

**Comment by fturmel** [comment]
> FYI the shiffman.net website is archived here! https://shiffman-archive.netlify.app/a2z/
> 
> I'm not maintaining it so I moved it off of shiffman.net (which now forwards to thecodingtrain.com) but I'm happy to link to any old but still useful material.

Makes sense, I'll link there instead. I also opened a PR to fix the quick links in the archive https://github.com/shiffman/shiffman.net/pull/136

> I prefer to recreate the code examples from the videos as p5 web editor examples (if they don't require node.js). I have some working wordnik examples as part of my last fall class's materials: https://editor.p5js.org/a2zitp/collections/cgfJWhpsE Maybe I could update the code?

These still work (are you OK leaking all these API keys though...?). It's only the word search API endpoint used in the "acrostic" challenge that seems to have been shut down (they say "deprecated" in their message, but it stopped returning data altogether).
https://github.com/CodingTrain/Coding-Challenges/blob/main/073_Acrostic/P5/sketch.js#L8

@kfahn22 That's awesome, thanks! Datamuse seems like a good substitute for this. I'll link to your sketch directly for now, but let me know if the link changes if we move it to the [Coding Train user](https://editor.p5js.org/codingtrain/sketches), etc. Feel free to make the changes to the PR directly too if that's easier.

**Comment by shiffman** [comment]
Responses to some notes above and I'm good to merge this when ready!

1. The YT Description has been updated. I'll run the description generator again when this is finalized in order for any last updates. This is a good excuse for me to test #1621 by @dipamsen.
2. When I put API keys in my examples I make sure they are "dummy" keys that I don't mind being shut off and I also try (I could do better) to talk about the risks and considerations of putting API keys in code. So, I guess that's a long answer to yes, I don't mind leaving the API keys in. 

I removed the CSS styles, added a thank you to @kfahn22 in the comments, and saved it under the CT account:

https://editor.p5js.org/codingtrain/sketches/48yinqNpT

**Comment by shiffman** [comment]
Fun idea!!

**Comment by shiffman** [comment]
Going to merge this and then test #1621, thanks everyone for the efforts to getting this challenge added to the site! It's not a terribly popular one but I'll be doing it with my students this week so having the page of resources will be so helpful!

**Pull request merged**
