### PR TITLE
Showcase Submission for code/6-objects/3-constructor

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Nathan Rudasill for your contribution! A member of the Coding Train team will review it shortly.

* [Sudoku Solver](https://editor.p5js.org/nrudasill/sketches/A0ANL-Q8U)
* Nathan Rudasill

preview image

### CODE REVIEW

**Comment by shiffman** [comment]
Wow! I would love to do this as a coding challenge! I'm happy to merge this here but I wonder if it might make sense to add to https://thecodingtrain.com/challenges/171-wave-function-collapse instead?

**Comment by shiffman** [comment]
If anyone wants to help move this showcase to WFC, please go ahead!

**Comment by kfahn22** [comment]
I have moved to WFC

**Comment by shiffman** [comment]
Thank you @kfahn22!

**Pull request merged**
