### PR TITLE
Update Footer.js

### PR DESCRIPTION
**Pull request by YadlaMani**
upated the twitter logo

### CODE REVIEW

**Comment by YadlaMani** [comment]
add the hacktoberfest label

**Comment by shiffman** [comment]
Not sure why this failed, can you elaborate on the icon you've chosen and the changes you propose to make? Glad to consider it, thank you!

**Comment by YadlaMani** [comment]
@shiffman just added new twitter logo from react-icons in gooter

**Comment by fturmel** [comment]
If @shiffman wants the change, I'd prefer if the icon came from the Font Awesome 6 set like the others, so essentially `FaXTwitter` from `react-icons/fa6`.

The icon is also in the `about` page, not just the footer.

Would you only change the icons and not the labels and keep calling it "Twitter"?

**Comment by shiffman** [comment]
To be honest, I think I prefer just leaving it as is. However, I do appreciate you @YadlaMani taking the time to engage with this repo! Is there something else you would like to work on? I suggest opening an issue to propose an idea and discuss before submitting a PR. All that said, I would consider @fturmel's suggestion and change the icon (but leave the text as "Twitter."

**Comment by YadlaMani** [comment]
@shiffman is there any issue i could take upon I am willing to contribute to the repo

**Comment by shiffman** [comment]
Hi @YadlaMani! I'm going to close this PR, I tried doing a little bit of maintenance today on the PRs and open issues, feel free to look through https://github.com/CodingTrain/thecodingtrain.com/issues and comment if there is something you'd like to work on!

**Pull request closed without merging**
