### PR TITLE
Site guides

### PR DESCRIPTION
**Pull request by klinegareth**
This PR adds draft site maintenance and passenger showcase guides to the site

### CODE REVIEW

**Comment by fdoflorenzano** [comment]
Hi @klinegareth, I think maybe a couple messages I sent you in slack last week got lost regarding this PR. I'll copy them here just in case:

@klinegareth  I accidentally overwrote the changes in the guides in your PR when trying to merge main in and resolve. I’ll try to bring them back now.

@klinegareth I just pushed the changes back as I think they were. Something weird happened when I merged main and I couldn’t get the original changes that you did. So maybe copy the files elsewhere before pulling, to get a back up, and then pull and check if all the changes are alright. I also pushed the fixes to make the images work.

**Comment by kfahn22** [comment]
I am not exactly sure what the language for the contributions guide is currently (maybe this has already been dealt with), but I think it needs to be clear that the folder is called "showcase".   The key change is in the last sentence.  

Creating the contribution file
Once in the showcase folder of the video, click "Add file" in the upper right-hand corner and click "Create new file" (or "Upload files'', if you already have the contribution on your local machine). Name the file contribution1.json (or if the file already exists, contribution2.json, if that exists contribution3.json, etc).   If there are no contributions, name the file showcase/contribution1.json.

**Comment by shiffman** [comment]
There is more to do for these guides but I think I'd like to merge and make changes / updates in another round of work. @fdoflorenzano any objections?

Also, it looks like the build process results in some lower quality screenshot images on this guide page. Perhaps it's a way we are preparing them? @fdoflorenzano do you have any advice or tips?

The images @klinegareth created are full browser screenshots, I experimented with doing a "zoomed in" snapshot of a part of a page. I'm glad to redo these to conform to whatever standards we feel will look best!

**Comment by fdoflorenzano** [comment]
> There is more to do for these guides but I think I'd like to merge and make changes / updates in another round of work. @fdoflorenzano any objections?

I don't! I was waiting for @klinegareth 's confirmation on my previous comment to review the content and make pointers, but I can do that in separate issue or PR.

> Also, it looks like the build process results in some lower quality screenshot images on this guide page. Perhaps it's a way we are preparing them? @fdoflorenzano do you have any advice or tips?
> 
> The images @klinegareth created are full browser screenshots, I experimented with doing a "zoomed in" snapshot of a part of a page. I'm glad to redo these to conform to whatever standards we feel will look best!

I'm guessing that the original image is just too small and gets stretched out in Gatsby when trying to resize for multiple screen sizes. Using the branch name picture as an example, maybe something you can try is zooming in your browser, so that the section you screenshot is bigger as a picture. The bigger the picture, the better I think is the way to go.

**Pull request merged**
