### PR TITLE
Update contributing and content structure guide

### PR DESCRIPTION
**Pull request by dipamsen**
Updated
- [CONTRIBUTING.md](https://github.com/dipamsen/thecodingtrain.com/blob/update-guides/CONTRIBUTING.md)
  - Moved the "Getting Started" section (which links to `content-structure-guide`) above the more specific contributing instructions (?)
  - Removed challenge porting (only 2 challenges yet to be ported)
  - Added "Add a new track to the site" (specifically for side tracks)

- [content-structure-guide.md](https://github.com/dipamsen/thecodingtrain.com/blob/update-guides/content/pages/guides/content-structure-guide.md) (Internal guide defining content structure)
  - Mainly updates in content structure, including new fields (`nebulaSlug`, `canonicalTrack`, `credits`, social usernames for showcases, `submittedOn`) and new behaviour (randomisation).

Created 
- [HACKTOBERFEST.md](https://github.com/dipamsen/thecodingtrain.com/blob/update-guides/HACKTOBERFEST.md)

May also want to update
- [ ] website-maintainance-guide.md  ? (guide on the website for website maintainers)
- [ ] passenger-showcase-guide.md

### CODE REVIEW

**Comment by dipamsen** [comment]
> 1. Share your creative work inspired by a coding challenge or tutorial in the showcase!
> 
>  - You can submit your showcase with the [Passenger Showcase Form](http://thecodingtrain.com/submit)

Specifically for Hacktoberfest, using the passenger showcase form does not contribute to a PR under their github account, so we should also add info about manual submissions.

**Comment by kfahn22** [comment]
I think we should add detailed instructions for how to add a manual showcase.  Also need to add a link to the new repo created by @shiffman

https://github.com/CodingTrain/Coding-Train-Logo

**Comment by dipamsen** [comment]
@shiffman should the contributing.md be updated to be specifically for Hacktoberfest (like last year)? Or would you prefer a separate md file just for hacktoberfest (which will contain all the ways to contribute to Hacktoberfest with The Coding Train, as you mentioned on the live stream)?

**Comment by shiffman** [comment]
> @shiffman should the contributing.md be updated to be specifically for Hacktoberfest (like last year)? Or would you prefer a separate md file just for hacktoberfest (which will contain all the ways to contribute to Hacktoberfest with The Coding Train, as you mentioned on the live stream - including Logo, other repos, etc.)?

I'm good either way if you think one is better! Maybe it makes sense to have a separate file so that it's easier to maintain every year just activating a link from the main README on Oct 1?

**Comment by dipamsen** [comment]
I created a `HACKTOBERFEST.md` file showing the ways to contribute to the Coding Train during Hacktoberfest.

**Comment by shiffman** [comment]
This is fantastic, thank  you @dipamsen for this incredible work!

**Pull request merged**
