### PR TITLE
Showcase Submission for challenges/181-image-stippling

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Geoffrey Wagner for your contribution! A member of the Coding Train team will review it shortly.

* [Far Side Cartoon - Trophies](https://github.com/Cyberdine2/RaspberryPi/tree/main/VelonaiStipling)
* Geoffrey Wagner

preview image

### CODE REVIEW

**Comment by shiffman** [comment]
@Cyberdine2 is the repo perhaps private? The link goes to a 404 page

**Comment by Cyberdine2** [comment]
yes it is

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cyberdine2** [comment]
not sure if it's what you are looking for, i just invited the Shiffman github to collaborate,or doe the whole thing need to be in public view?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by shiffman** [comment]
> not sure if it's what you are looking for, i just invited the Shiffman github to collaborate,or doe the whole thing need to be in public view? 

There's no requirement that the code or your repo be public, but the link you add to the website could be clicked on by anybody, so I would suggest creating a webpage that has info about your showcase project or if you don't want to do that you could just link to your main github account page.

**Comment by Cyberdine2** [comment]
Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Cyberdine2** [comment]
Do i need to resubmit? I wouldn't say it's hardly that important, nothing really worth showing off on a website nut maybe soon, really just random shenanigans. I bought the raspberry pi 5 , planned to put a webpage on, got the upgrade router with port forwarding, had the full intention of using it for hosting a webpage, i like using it too much. So no website, yet. it's more for the sake of having it on the coding train community page. My instructor 3 or so years ago said i should keep my github private for anyone but the collage.

https://github.com/Cyberdine2

this one?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cyberdine2** [comment]
Here this for the farside one

https://editor.p5js.org/cyberdine1988/sketches/i2ebK33jL

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by Cyberdine2** [comment]
ok, sorry forget all of that. I have opened a new repo "PublicRepo", i will make 4 new submissions on the coding train website from that repo instead .

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by shiffman** [comment]
great! I'll merge the new ones.

**Pull request closed without merging**
