### PR TITLE
Porting CC 40 Word Counter

### PR DESCRIPTION
**Pull request by DenisovichDev**
Sorry to be absent for a while, but I'm back to maintaining again.

To-do:
- [x] 40.1 Word Counter in p5.js
- [x] 40.2 Word Counter in Processing
- [x] 40.3 TF-IDF
- [x] Related challenges

### CODE REVIEW

**Comment by fturmel** [comment]
btw the videos don't load properly if you use the full YouTube URL in the `videoId` fields: https://deploy-preview-825--codingtrain.netlify.app/challenges/40-word-counter

**Comment by fturmel** [comment]
@DenisovichDev Need any help finishing this PR?

Are you just missing related challenges? Some options:

https://thecodingtrain.com/challenges/44-afinn-111-sentiment-analysis
https://thecodingtrain.com/challenges/43-context-free-grammar
https://thecodingtrain.com/challenges/42-markov-chain-name-generator
https://thecodingtrain.com/challenges/39-madlibs-generator
https://thecodingtrain.com/challenges/37-diastic-machine
https://thecodingtrain.com/challenges/48-white-house-social-media-data-visualization
https://thecodingtrain.com/challenges/84-word-definition-chrome-extension
https://thecodingtrain.com/challenges/75-wikipedia-api

**Comment by DenisovichDev** [comment]
Thanks @fturmel! I just got busy irl and forgot that I had this PR open, I'll get back into it tonight. Also need to check why the merge just failed.

**Comment by fturmel** [comment]
@DenisovichDev Great! We added more thorough content checks, which is why the unit tests are failing.

- `videoId` values should be the YouTube ID, not a full URL
- Challenge videos need at least one `relatedChallenge`
- You're missing the `credits` property, which is now required. Most likely just the following:
```json
  "credits": [
    { "title": "Editing", "name": "Mathieu Blanchette" },
    { "title": "Animations", "name": "Jason Heglund" }
  ]
```

Per the spreadsheet in #155, the only challenges not migrated to the site yet were previously claimed by you. I'm wondering if you still wanted to work on these, or maybe want to release these do that community members can help finish these? Again, happy to help!

**Comment by DenisovichDev** [comment]
Thank you so much for your help @fturmel! I think I'll finish this PR now with your suggested edits, and free the rest of the ones that I had claimed and couldn't seem to finish to get this done quickly. I feel bad for holding these hostage and not being able to find time to port them for these last few months. Please feel free to update the spreadsheet as necessary. I did have some plans with some of the Challenges that are left since some of them have APIs that no longer seem to work among other things, but I suppose I can work of that after they are ported as well. I hope to find some time in future to become active again.

**Comment by kfahn22** [comment]
@DenisovichDev I hope you don't mind, I just added an index image.  I think this is ready for review, correct?

**Comment by shiffman** [comment]
Amazing!

**Pull request merged**
