### PR TITLE
Porting CC 47 Pixel Sorting in Processing

### PR DESCRIPTION
**Pull request by anusha-exe**
Things that have been done:

- checked and cleaned up links and tags
- added timestamps
- updated the thumbnail according to the requirements. I don't know if this is okay. Feel free to change it as you see fit.
- added screenshot of the showcase
Related challenges section needs to be updated since Quick Sort Visualization hasn't been ported yet.

### CODE REVIEW

**Comment by kfahn22** [comment]
Thank you!!  I have a couple of updates, otherwise this looks great!  

I would use the image of sunflowers for the code image.  I can update that if you would prefer.

The link to the Processing code should be updated  because the prior repo is now archived.  Here is the new link.
https://github.com/CodingTrain/Coding-Challenges/tree/main/047_PixelSorting/Processing

**Comment by anusha-exe** [comment]
@kfahn22  Thank you for the corrections! I have changed the index.jpg and the Processing code link. Please check if everything's fine now

**Comment by kfahn22** [comment]
Thank you, this looks great!  I apologize, I loved your original index image!   I was only suggested that you  add a code example image since the png file in the code sketch is sunflowers but I didn't make that very clear.

**Comment by anusha-exe** [comment]
Ah, I didn't realize. I'll make the changes, no problem

**Comment by shiffman** [comment]
Thank you for this wonderful contribution!!

I love that you are creatively trying a new image for this and using the Coding Train background! I think that image, however, doesn't demonstrate pixel sorting so well because the source image has something of a sorted gradient sky. So I might suggest using he sunflower or else do you want to try a different Coding Train specific image?

**Comment by kfahn22** [comment]
pixel
Sorry for the extra work I have caused you!  Here is an image of Daniel and Gloria that you can  use if you want.

**Comment by anusha-exe** [comment]
@kfahn22 I don't mind that at all! How can anyone keep anything but this after looking at this image TT. Thank you! I'll be using this then, @shiffman

**Pull request merged**
