### PR TITLE
My Bubble Sort Visualization!

### PR DESCRIPTION
**Pull request by AyushKoul00**
This is a submission of my bubble sort visualization!

### CODE REVIEW

**Comment by AyushKoul00** [comment]
@shiffman sure no problem. I just wanted to contribute to a repo with hactoberfest. Since I wasn't sure whether that was the case with the new website repo, I submitted a PR here as well

**Comment by shiffman** [comment]
Thanks @DenisovichDev topics and about are updated now! I added the label here, shall I try merging?

**Comment by DenisovichDev** [comment]
Yes everything looks good now! There isn't actually much left that can be done at this point. If this doesn't get picked up, there's still plenty of time for the contributor to make more contributions!

**Comment by shiffman** [comment]
@AyushKoul00 would you like to add a thumbnail image before I merge this? If no image is provided it just uses the code example image itself. More info at: https://thecodingtrain.com/guides/passenger-showcase-guide

**Comment by AyushKoul00** [comment]
@shiffman the default image is fine. Thank you!

**Comment by shiffman** [comment]
Sure happy to try that!

**Pull request closed without merging**
