### PR TITLE
Showcase Submission for 27-fireworks

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Captain Yass for your contribution! A member of the Coding Train team will review it shortly.

* [house change](https://editor.p5js.org/Yassine.meb/full/qS18iNTpO)
* Captain Yass

preview image

### CODE REVIEW

**Comment by shiffman** [comment]
Lovely work! This looks like it maybe goes with the "random" video? would you like to submit it there or would you like us to move it for you?

https://thecodingtrain.com/tracks/code-programming-with-p5-js/code/2-variables/4-random

**Comment by shiffman** [comment]
Ah, I think this was submitted by a passenger without a github account so this notification probably goes nowhere! Let's move it, I can't this very second, but will return back to it or anyone else is welcome to take care of it!

**Comment by dipamsen** [comment]
Moved!

**Comment by shiffman** [comment]
Thank you @dipamsen!

**Pull request merged**
