### PR TITLE
Showcase Submission for 117-seven-segment-display

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Theia Emily for your contribution! A member of the Coding Train team will review it shortly.

* [Dozenal (Base-12) 7-Segment Clock](https://editor.p5js.org/theiaemilyheinig/full/jH8wHmJzr)
* [Theia Emily](https://youtube.com/@theiaemily9010)

preview image

### CODE REVIEW

**Comment by fturmel** [comment]
@dipamsen It worked, but the Netlify GitHub plugin is not reflecting the rebuild state. Lots of weird behaviors with GitHub actions on this repo over the last few days.

Screenshot 2023-06-01 at 1 21 17 PM

Screenshot 2023-06-01 at 1 22 34 PM

**Comment by dipamsen** [comment]
@fturmel ig the checks following the deploy are not rerun during a manual deploy?

**Comment by fturmel** [comment]
> @fturmel ig the checks following the deploy are not rerun during a manual deploy?

It's possible that I'm wrong, but I thought these used to refresh and sync up properly. The "Latest deploy log" link did update at least.

**Comment by dipamsen** [comment]
oh ok that makes sense, I also think it is supposed to do it automatically,

**Comment by shiffman** [comment]
I'm attempting to make an edit to force a rebuild, will switch it back if it works.

**Comment by shiffman** [comment]
I love this so much!

**Pull request merged**
