### PR TITLE
Passenger showcase contribution from J G Valentim Rocha

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Yay!

### CODE REVIEW

**Comment by shiffman** [comment]
Thank you @xValentim for this wonderful contribution! Do you have permission to use the photo featured in the project? I want to make sure before I merge it onto the site. Thank you!!

**Comment by xValentim** [comment]
> 

Yes, I have permission to use all photos in my projects.

**Comment by xValentim** [comment]
> Thank you @xValentim for this wonderful contribution! Do you have permission to use the photo featured in the project? I want to make sure before I merge it onto the site. Thank you!!

Thank you for all videos on coding train. Iam really a big fan of you! And I have permission for all photos on my project.

**Comment by xValentim** [comment]
Hello!

Thank you for every project and challenge on Coding Train. Iam really a big fan of you.
Yes, I have permission to use all photos in my projects.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
