### PR TITLE
Improve content test for `videoId` field

### PR DESCRIPTION
**Pull request by fturmel**
#1655 made me realize that there was an error in the way the video schema was defined, and it was allowing empty `videoId` to pass the tests.

The check was also updated so that the top-level `videoId` must be empty or undefined instead of optional when a video is multi-part. It should help avoid confusion and information repetition.

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @fturmel thanks again! Am I confused or is there a mistake in this PR where a bunch of videoIds are removed? Perhaps that is leftover from testing the tests themselves?

**Comment by shiffman** [comment]
Hi @fturmel thanks again! Am I confused or is there a mistake in this PR where a bunch of videoIds are removed? Perhaps that is leftover from testing the tests themselves?

**Comment by fturmel** [comment]
No it's intended, sorry I wasn't clear. There's a bug fix and an improvement in there:

* The existing schema validation was supposed to make sure that `videoId` was required, but the "parts" argument was not destructured from the argument properly. It's basically a `Yup` library API usage mistake.

* The top-level videoIds removed are all for multi-part videos and were effectively useless. I added a check in the content tests to require them to be undefined or empty when a "parts" array exist. Currently they were optional but you could still put a YouTube ID in that field even if it did nothing.

**Comment by shiffman** [comment]
Ah, I see! Thank you for the clarification. Would it be more clear to remove the field entirely rather than have it as a blank entry?

**Comment by fturmel** [comment]
> Ah, I see! Thank you for the clarification. Would it be more clear to remove the field entirely rather than have it as a blank entry?

Sure, we can make the check more strict instead of being falsy (which allows undefined, null or empty string). Update incoming.

**Comment by fturmel** [comment]
Done, the `videoId` field cannot be present anymore if the video is multi-part.

**Comment by shiffman** [comment]
Fantastic!

**Pull request merged**
