### PR TITLE
Modified the url class in `--reduced` size in the `LinkList.module.css` file

### PR DESCRIPTION
**Pull request by zvolcsey**
Hi, I modified the url class in `--reduced` size in the `LinkList.module.css`. I opened the website in development mode and that seems to have fixed the problem.

### CODE REVIEW

**Comment by zvolcsey** [comment]
Close #798

**Comment by dipamsen** [comment]
Can confirm the issue is fixed.

**Comment by zvolcsey** [comment]
Sorry, then I work on it yet. Thanks the review. :)

**Comment by shiffman** [comment]
@allcontributors add @zvolcsey for code

**Comment by shiffman** [comment]
Thank you, this is great!

**Pull request merged**
