### PR TITLE
Showcase Submission for processing

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Garrett for your contribution! A member of the Coding Train team will review it shortly.

* [Creative Coding for Beginners - Full Course!](https://youtu.be/4JzDttgdILQ?si=fkisWGGb9vDVxUHr)
* Garrett

preview image

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @IFGARRETT it looks like you linked to the video itself! Do you want to link to a personal website or social media where you post the screenshot of your lovely creature?

**Comment by shiffman** [comment]
I'm going to allow this one to be merged b/c the image includes the code and fully shows the project! But if we can ever find a different place to link to that might be nice!

**Comment by IFGARRETT** [comment]
Sorry I'm new to all this so if I did it incorrectly I apologize. Thank you
though!

**Comment by shiffman** [comment]
You are doing great! We're all learning! Congrats on your first showcase submission! If you want help learning how to publish your Processing code and link to it from the showcase, feel free to ask!

**Comment by IFGARRETT** [comment]
Is this actually Mr. Shiffman replying? Either way thank you, some of this
is really complicated for me and I find myself hitting a mental wall not
knowing how to proceed. I am watching the learning to process video back
and forth over and over until I get certain things. Thank you so much for
your help!

**Comment by shiffman** [comment]
Glad to help! You can also ask more question in discord: https://thecodingtrain.com/discord

**Pull request merged**
