### PR TITLE
Adding 44 afinn 111 sentiment analysis

### PR DESCRIPTION
**Pull request by borntofrappe**
The live demo is quite heavy on text, so I tried to summarize the most important visuals in `index.jpg`.

index image

Hopefully it is enough to illustrate the technique with the AFINN list.

### CODE REVIEW

**Comment by anusha-exe** [comment]
I'd like to mention a little thing, if you don't mind. The commas should have been after the number with the space following it. `great: 2, good: 3`

**Comment by anusha-exe** [comment]
I'd like to mention a little thing, if you don't mind. The commas should have been after the number with the space following it. `great: 3, good: 3`

**Comment by borntofrappe** [comment]
Thanks for the mention @anusha-exe. It makes a world of a difference

**Comment by shiffman** [comment]
This looks so good thank you!!

**Comment by anusha-exe** [comment]
Glad to be of help! The thumbnail looks great

**Pull request merged**
