### PR TITLE
[WIP] Adding CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by DenisovichDev**
I have made a preliminary version of the `CONTRIBUTING.md` file. Still needs a bit of work though. @kfahn22 please feel free to change or add whatever you think should be changed or added.

I have added some stuff from the old repo `CONTRIBUTING.md`, but I feel like there could be more things to add

### CODE REVIEW

**Comment by borntofrappe** [comment]
Hope you don't mind a small update @DenisovichDev 

The link for the _Passenger Showcase Guide_ in the _Getting Started_ section sends to a missing page. It seems the URL has one `s` letter more than necessary and should actually point to [/guides/passenger-showcase-guide](https://thecodingtrain.com/guides/passenger-showcase-guide).

The reference to the README for the repository also leads to a 'Not found' page. Either of the following should highlight the correct information.

- https://github.com/CodingTrain/thecodingtrain.com#readme
- https://github.com/CodingTrain/thecodingtrain.com/blob/main/README.md

**Comment by DenisovichDev** [comment]
@borntofrappe Thank you for pointing that out! I forgot to check the links before pushing, my bad

**Comment by kfahn22** [comment]
@DenisovichDev I think it looks great! I am not sure that they are necessary, but  I made a couple of changes and have in patch here.  https://github.com/kfahn22/thecodingtrain.com/blob/patch/CONTRIBUTING.md

**Comment by shiffman** [comment]
This is terrific! I really appreciate all the effort going into this. @kfahn22 would you like to pull request some of your changes here, you might have to manually re-enter them (or else perform some gymnastics between the various branches). I can merge this one first if it makes things simpler. 

I'm also happy to pull what I like from your version but then the commits won't get registered to you! Let me know!

**Comment by shiffman** [comment]
After reading it over I think it make sense to merge then @kfahn22 and I can add any suggestions or additional edits separately!

**Comment by DenisovichDev** [comment]
Thanks @shiffman and @kfahn22!

**Pull request merged**
