### PR TITLE
Learning Processing

### PR DESCRIPTION
**Pull request by dipamsen**
- [x] Cover Image

image

image

image

🚂 [Deploy Preview](https://deploy-preview-1214--codingtrain.netlify.app/tracks/learning-processing)

### CODE REVIEW

**Comment by shiffman** [comment]
Looking great! I added a credit for @melissa-rodriguez. I can't remember, do the credits support URLs? I think they do. We can link to a social media profile or website if you like @melissa-rodriguez!

**Comment by fturmel** [comment]
@dipamsen heads up - I had the timestamps validator in the content tests only accept up to 4:59:59, but it looks like this video will legitimately go over that limit. Here's the regex to update:

https://github.com/CodingTrain/thecodingtrain.com/blob/ffc1f8565309cc3510a8de0ce92fadd212b6697a/content-testing/format-augmented.test.js#L156-L157

**Comment by melissa-rodriguez** [comment]
Sure! You can link to my Instagram:
https://www.instagram.com/hellomelissarodriguez/

**Comment by blinkityblank** [comment]
Here are the updated timecodes for the sections of the YouTube video.
Timestamps:
0:00:00 INTRODUCTION
0:17:30 DRAWING WITH CODE
1:04:39 FLOW
1:29:31 VARIABLES
2:02:46 CONDITIONALS
2:50:01 LOOPS
3:12:29 ARRAYS
3:40:29 FUNCTIONS
4:02:30 CLASSES AND OBJECTS
4:56:20 CONFETTI PROJECT
5:03:15 CONCLUSION

**Comment by shiffman** [comment]
Merging in advance of YouTube release tomorrow!

**Pull request merged**
