### PR TITLE
Fix content urls

### PR DESCRIPTION
**Pull request by fturmel**
I wrote some code to extract urls from all content files to see if we got non-2xx statuses or network issues when trying to connect to them. This PR corrects mostly basic redirects (http -> https, trailing slashes, url changes), but there were definitely some broken links in there.

Some questions:
- [Paddle angles drawing](https://i1.wp.com/zekechan.net/wp-content/uploads/2015/07/pong-05b.png?resize=600%2C500) url seems dead and no wayback machine backups. This is a link in the Pong challenge (67). Should we remove the link, is there another URL that can serve as a substitute for what this was illustrating?
- [deeplearnjs.org](https://deeplearnjs.org) was linked in the XOR challenge (92) but it just redirects to the TensorFlow.js site now. Should we just update the link and copy to go directly to TensorFlow?
- The [ROBERT KRULWICH](https://www.wnycstudios.org/shows/radiolab) link redirects to radiolab.org in the Chaos game challenge (123). He's not involved with the podcast anymore. Do you want to keep the Radiolab link? Some alternatives:
  - https://www.wnycstudios.org/people/robert-krulwich
  - https://en.wikipedia.org/wiki/Robert_Krulwich
- In the [about page](https://thecodingtrain.com/about), I suspect that the links for Mathieu Blanchette and Dusk Virkus are wrong. Placeholders that were left there accidentally?

This was not an exhaustive process btw, there can still be bad urls for us to find. For example, the p5js editor's [404 sketch page](https://editor.p5js.org/codingtrain/sketches/not-an-actual-sketch) actually returns a 200 status code... We might need a better automated solution with screenshots if we want to be more thorough.

We should also tackle bad urls from the showcase contributions eventually. I anticipate it'll be much more time-consuming.

### CODE REVIEW

**Comment by fturmel** [comment]
@shiffman Little update on this PR, I found 3 additional bad links to p5js sketches. Are you able to re-upload the code to a new sketch, or should the links be removed?

https://github.com/CodingTrain/thecodingtrain.com/blob/908f29a2c34fa076c33c2ed4332cd055327a669e/content/videos/ml5/7-posenet/2-pose-classifier/index.json#L54

https://github.com/CodingTrain/thecodingtrain.com/blob/908f29a2c34fa076c33c2ed4332cd055327a669e/content/videos/code/1-intro/4-color/index.json#L35

https://github.com/CodingTrain/thecodingtrain.com/blob/908f29a2c34fa076c33c2ed4332cd055327a669e/content/videos/noc/5-autonomous-agents/6-scalar-projection/index.json#L39

**Comment by dipamsen** [comment]
@fturmel 

1. ml5 track: 7.2 Pose Classifier
Looks like some code examples in that file are wrongly labelled, Here are the correct code examples ([source](https://editor.p5js.org/codingtrain/sketches/JoZl-QRPK)):
```
// All code: https://editor.p5js.org/codingtrain/sketches/JoZl-QRPK

// Separated into steps
// 1: Data Collection: https://editor.p5js.org/codingtrain/sketches/kTM0Gm-1q
// 2: Model Training: https://editor.p5js.org/codingtrain/sketches/-Ywq20rM9
// 3: Model Deployment: https://editor.p5js.org/codingtrain/sketches/c5sDNr8eM
```

Also, the title field of that file is incorrect , it should probably say "Pose Classifier with PoseNet and ml5.neuralNetwork()"

2. Code! Track: 1.4 Color
I cannot find that NOC example sketch. It is not really a code example for that video though, so I guess it can be removed (?)

3. NOC Track: 5.6 Scalar Projections
I found this version of that sketch: `https://editor.p5js.org/codingtrain/sketches/f2ai9bTCt`
I believe it is the same sketch as that demonstrated in the video, it just has  been moved to the `codingtrain` account.

**Comment by fturmel** [comment]
@dipamsen thanks for that, I made the corrections.

And you are right, the oscillation sketch is referred to in the video at https://youtu.be/riiJTF5-N7c?t=82 but it's just a random sketch selected to demonstrate how to edit and duplicate a p5js sketch. It should be safe to remove the link.

**Comment by shiffman** [comment]
Some respones @fturmel:

> paddle angles

I can't find anything so let's just remove?

* [deeplearnjs.org](https://deeplearnjs.org/)

Yes, I think we can link directly to tf.js

* Robert Krulwich
Let's do WNYC: https://www.wnycstudios.org/people/robert-krulwich

* In the [about page](https://thecodingtrain.com/about), I suspect that the links for Mathieu Blanchette and Dusk Virkus are wrong. Placeholders that were left there accidentally?

Yes, let's remove these, links are only there if requested / provided by the people listed

Thank you!!!!

**Comment by fturmel** [comment]
@shiffman Great, made the changes. This should be ready to merge.

**Pull request merged**
