### PR TITLE
Added hover state to the PassengerShowCaseForm's button

### PR DESCRIPTION
**Pull request by zvolcsey**
Hey, I added missing hover state to the submit button. 
I like The Coding Train channel on Youtube. Thank you for the many useful videos and articles. :) Have a nice day!

### CODE REVIEW

**Comment by shiffman** [comment]
Thank you for taking a look at this! In the deploy preview the button now animates with random colors but the cursor does not change to a hand.

https://deploy-preview-545--codingtrain.netlify.app/guides/passenger-showcase-guide

I'm in chrome on a mac, is this the behavior you see too?

**Comment by zvolcsey** [comment]
Thanks for reviewing! It works as expected on windows for me. Chrome version: 105.0.5195.102 (Official Build) 64bit. I asked a friend to test on macos. Chrome Version 105.0.5195.102 (Official Build) (arm64) and macOS Monterey 12.5.1 (21G83). It worked as expected. Which version did you use?

Test on macos:
https://user-images.githubusercontent.com/41576384/189524757-c2fcceb1-a277-426b-834b-05a11975e88c.mov

**Comment by lobertrand** [comment]
I have a hand cursor on Linux (Google Chrome 103.0.5060.134 (Official Build) (64 bits))

**Comment by shiffman** [comment]
Weirdly, this is an issue across the board for me (not unique to CT site) where the cursor is misbehaving. I probably just need a restart. Thank you so much, apologies for the confusion, excited to merge!

**Pull request merged**
