### PR TITLE
Add new Coding Train Live! track

### PR DESCRIPTION
**Pull request by kfahn22**

### CODE REVIEW

**Comment by dipamsen** [comment]
maybe this doesn't need credits? 😅

**Comment by dipamsen** [comment]
Also, in the future it might be useful to have a "Live" section on the site, or feature this track on the homepage; if there ends up happening multiple project live streams.

**Comment by kfahn22** [comment]
I agree it doesn't need the credits, but it fails the tests w/o them.  Also, I am under the impression that there are a lot of videos on the site that haven't been edited that have the credits.

I am not sure where the best place to put the livestream videos is, but this was an easy way to add the video and allow people to start contributing  their own versions.

**Comment by dipamsen** [comment]
For the credits, I think providing an empty array will pass the tests.

**Comment by shiffman** [comment]
I think this is a great start! Ideally, I would love to annotate and document every single live stream and have a separate section of hte website like challenges, tracks, but I think that's too big of an undertaking and unrealistic to do right now. So I track for "select" livestreams makes a lot of sense! 

I don't feel too strongly about the credits, it's true they don't apply for livestreams so maybe it makes sense to leave a blank array. @kfahn22 let me know when this is ready to merge! I'll review and see if I want to make any small edits too.

**Comment by kfahn22** [comment]
@shiffman I have tried passing a blank array and it is failing the content tests for me.  Other than that, it is ready for review.

**Comment by fturmel** [comment]
> @shiffman I have tried passing a blank array and it is failing the content tests for me. Other than that, it is ready for review.

You can remove the `min(1)` and/or `required()` rules on the credits field of the schema if you want to loosen the validation rule. Make sure to test that the site is able to handle an undefined or empty array value before merging!

https://github.com/CodingTrain/thecodingtrain.com/blob/3f59b50d8c3137a11c1f9083fa49c832145dc263/content-testing/schemas.js#L121-L129

**Comment by dipamsen** [comment]
I have changed the tests to allow for empty credits.

**Comment by shiffman** [comment]
Apologies for the delay, this is wonderful, thank you everyone! I'm going to go ahead and merge and we can always refine more later!

**Pull request merged**
