### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by supercrafter100**
This pull request contains a few spelling mistakes I have found in the new website.

### CODE REVIEW

**Comment by shiffman** [comment]
Fantastic, thank you!!!

**Comment by shiffman** [comment]
> I'm unsure where `NVideo RTX Broadcast` is from? I can only find `NVIDIA Broadcast App`? Referencing [this line](https://github.com/CodingTrain/thecodingtrain.com/blob/main/content/pages/faqs/how-livestream-and-record.json#L7)

Yes! NVIDIA Broadcast App is correct!

**Comment by shiffman** [comment]
Seems like you are finding more and more! Let me know when your review is complete and then I will merge!

**Comment by supercrafter100** [comment]
I've noticed that the file "mantain-website-guide" is misnamed and likely outdated since it looks like the things mentioned in it are not correct anymore. It will probably need to be partially rewritten to apply to the new website so i've stopped further spelling fixing in it for now.

**Comment by supercrafter100** [comment]
I'm actually going to undo the renaming of the file since i'm unsure if it will break things (likely will). Someone else will have to fix that one.

**Comment by supercrafter100** [comment]
Think i'm done here! I've read through most things now. Will create another PR if I find another issue later on maybe. Thanks for waiting!

**Comment by shiffman** [comment]
❤️

**Pull request merged**
