### PR TITLE
Ported CC 037 Diastic Machine

### PR DESCRIPTION
**Pull request by DenisovichDev**
This PR ports CC 37 Diastic Machine.

- Have added a thumbnail with coding train colors
- Added thumbnails
- Added related challenges

### CODE REVIEW

**Comment by shiffman** [comment]
@DenisovichDev we can also replace the image after merging if you prefer! I think your placeholder is great and I bet @kfahn22 will have an idea of how to bedazzle it with Coding Train colors!

**Comment by DenisovichDev** [comment]
Alright, I'll add something with the colors, and maybe it could be revised  in a different PR

**Comment by DenisovichDev** [comment]
I added a thumbnail and timestamps! This is ready to be reviewed now

**Comment by shiffman** [comment]
Sorry @DenisovichDev, it seems some conflicts have emerged would you be able to take a look again? If not, don't worry, I'm glad to investigate more myself!

**Comment by shiffman** [comment]
I fixed it but since I don't have permissions to this branch on your fork I had to re-open the pull request, see #662. Your commits are still credited of course!

**Comment by DenisovichDev** [comment]
Thank you! What exactly was the conflict?

**Pull request closed without merging**
