### PR TITLE
Fixed expired Discord channel invite link

### PR DESCRIPTION
**Pull request by janez33**

### CODE REVIEW

**Comment by janez33** [comment]
In the spirit of Hacktoberfest I contribute to this project, I found a invalid link and fixed it :) Happy halloween 🎃

**Comment by DenisovichDev** [comment]
@janez33 Ah! Thank you for pointing out. Can you confirm if the link you shared is valid forever for infinite number of uses?

**Comment by janez33** [comment]
> @janez33 Ah! Thank you for pointing out. Can you confirm if the link you shared is valid forever for infinite number of uses?

I found it multiple times on this site on different pages, but probably only admin of the discord channel can confirm it.

**Comment by shiffman** [comment]
@KobeLiesenborgs is this the correct link we should use? Did I lose the `codingtrain` one by accident?

**Comment by shiffman** [comment]
Thank you for this @janez33! I marked it as `hacktoberfest-accepted` but will wait for Kobe before merging!

**Comment by KobeLiesenborgs** [comment]
Hi @janez33 ! 
We've restored our vanity URL but you pointed out a good issue where we should use our own general link (thecodingtrain.com/discord) so we have a single point of failure! Feel free to edit the pull request to use this link (otherwise I will tomorrow)
Thank you for your contribution!

**Comment by janez33** [comment]
@KobeLiesenborgs

**Comment by janez33** [comment]
@KobeLiesenborgs Can I change to this vanity url for every discord link you have?

**Comment by KobeLiesenborgs** [comment]
@janez33 you can change any link to the discord to become thecodingtrain.com/discord and the redirect for that link itself can point to the vanity url (discord.gg/codingtrain, this might change to "thecodingtrain" but when it does I'll pr it)

**Comment by janez33** [comment]
@KobeLiesenborgs Thank you, all discord links should be fixed now 👍

**Comment by shiffman** [comment]
Thank you so much @janez33 and @KobeLiesenborgs!

**Pull request merged**
