### PR TITLE
Created a new showcase submission in cc #178

### PR DESCRIPTION
**Pull request by raj-jaiswal**
Manually submitted a showcase in coding challenge #178 since the automatic submission from the website is not working. I was not sure about the number at the end of the file name so please check that.

### CODE REVIEW

**Comment by raj-jaiswal** [comment]
Here's the contribution image

**Comment by fturmel** [comment]
Thanks for submitting directly through GitHub! I think your image was just a _bit_ too large to get through the form submission. #1021 should address the 256 KB limit once completed.

**Comment by raj-jaiswal** [comment]
Thanks for the reply! I do think there should be a warning about file size when it gets too big. All it showed me was that it could not be submitted and to contact at the help email.

**Comment by shiffman** [comment]
Thank you for this! Yes, hopefully we'll have the issue resolved soon thank you for the submission and feedback @raj-jaiswal!

**Pull request merged**
