### PR TITLE
Adding Side Track: WebSockets and p5js

### PR DESCRIPTION
**Pull request by anusha-exe**
Seeing the issue #279 , I thought of starting with adding the side track for web sockets and introduction to node.

📝Tasks:
- [x] Side track metadata
- [x] Track thumbnail

Videos metadata:
- [x] 1-Introduction to Node
- [x] 2-Using Express with Node
- [x] 3- Connecting Client to Server using Socket.io
- [x] 4-Shared Drawing Canvas
- [x] showcase files and screenshots

~The only [link](https://github.com/CodingTrain/website-archive/tree/main/Node/sockets/public) to the code example that I found was in the website archive. So I'll be adding this to the `codeExamples` field~

Ready for [preview](https://deploy-preview-759--codingtrain.netlify.app/tracks) 🚂🚂

### CODE REVIEW

**Comment by dipamsen** [comment]
@shiffman The code examples for this track are only in the archived repository. Should it be in its own repo? I can move the code to a repo if you could create one.

**Comment by anusha-exe** [comment]
I'll change the link to the code example if it gets moved

**Comment by shiffman** [comment]
Yes, new repo is a great idea!

https://github.com/CodingTrain/sockets-and-p5

(Feel free to suggest a better repo name and document however you see fit!)

**Comment by anusha-exe** [comment]
@shiffman I have only added the description for now. I'll add an outline of the track with the links after it this gets merged if that's fine by you. I have changed the link in the index.json of the side track.

Also, in my local server deployment, I see the track thumbnail but I can't see it in the netlify deploy preview. Is it better to remove it?
Local deploy

**Comment by shiffman** [comment]
Incredible work! Merging!

**Pull request merged**
