### PR TITLE
Added noise videos to noise track for issue #1407

### PR DESCRIPTION
**Pull request by lcgraves**
I also added three missing thumbnail images for older showcase contributions (issue # 1057).

### CODE REVIEW

**Comment by kfahn22** [comment]
@lcgraves Thank you so much for adding the noise videos and images!!!  I have left some suggestions to help you edit the pull request so that it will pass the tests (I left the fixes for only one of the files, the comments about timecodes and credits applies to both).   You can also run `nom run test` in terminal  to see what the problems are. 

You will also need to edit the index.json file for the NOC track and add the videos so they will show on the website:

content/tracks/main-tracks/the-nature-of-code-2/index.json

{
      "title": "Perlin Noise and p5.js Tutorial",
      "videos": ["noc/perlin/intro-to-perlin-noise", "noc/perlin/noise-vs-random", "noc/perlin/graphing-1d-perlin-noise", "noc/perlin/perlin-noise-2d", "noc/perlin/perlin-noise-detail"]
    }, 

If you have any questions please let me know.  Again, thank you so much for contributing!

**Comment by shiffman** [comment]
Hi @lcgraves, wow, thank you for this wonderful contribution! Please let us know if you would like to finish any changes to this branch or if you prefer @kfahn22 or I can make final adjustments so it can be  merged.

Thank you for taking the time, and for your patience for me to review!

**Comment by shiffman** [comment]
@kfahn22 thanks for updating this! Is it ready for me to merge?

**Comment by shiffman** [comment]
@all-contributors add @lcgraves for content

**Comment by kfahn22** [comment]
Yes, I believe it is ready to merge.

**Pull request merged**
