### PR TITLE
Showcase Submission for challenges/182-apollonian-gasket

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Juan Carlos Ponce Campuzano for your contribution! A member of the Coding Train team will review it shortly.

* [Apollonian gasket precipitation](https://editor.p5js.org/jcponce/full/l5dSo59Ia)
* [Juan Carlos Ponce Campuzano](https://www.dynamicmath.xyz/)

preview image

### CODE REVIEW

**Comment by shiffman** [comment]
duplicate of #1519 ?

**Comment by dipamsen** [comment]
@shiffman hmm, not quite sure if it's a dupe as the url and title are different...

**Comment by jcponce** [comment]
Hi there! They are different! One is precipitation snowflakes and the other is collisions. Combinations of other Coding challenges :) 

Cheers!

**Comment by shiffman** [comment]
Apologies we get duplicates a lot so i didn't look super closely!

**Comment by jcponce** [comment]
No worries! :) I also thought it will considered as a duplicate since they screenshots are very similar. Thanks!

**Pull request merged**
