### PR TITLE
Side Track: Topics in Native JavaScript

### PR DESCRIPTION
**Pull request by dipamsen**
I have named this "Topics in Native JavaScript" as it is mentioned in #279. The original [playlist on youtube](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6YgpA3Oht-7B4NBQwFVe3pr) is called "Topics of JavaScript (ES6-ES8)". If a different name is preferred, let me know.

* Two videos - Classes and Constructor Arguments (6.2 and 6.3) are from the Code! track, so I have directly referenced these videos from its directory.

* For 10: Particle System with Array Functions, I did not find the code anywhere, so I created the sketch the p5 editor [here](https://editor.p5js.org/codingtrain/sketches/cFXgW95RZ).

* Videos 11-16 can be made into a side track "JavaScript Promise" / "Asynchronous JavaScript". ([corresponding playlist](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bKLPQvPRNNE65kBL62mVfx) on the Coding Train)

Preview: https://deploy-preview-449--codingtrain.netlify.app/tracks/topics-in-native-javascript

-----

image

image

### CODE REVIEW

**Comment by shiffman** [comment]
This is wonderful!

> ⚠️ Have not added code examples for videos 11-16 (Promises), because they do not exist in a repo/p5 editor. ([Link to code](https://github.com/CodingTrain/website-archive/tree/main/Tutorials/P5JS/16_promises))

What do you think would be best? Should I add all these to the web editor or create a new repo?

**Comment by shiffman** [comment]
> I am fine with both, I think since there are not many examples; we can use the web editor.

Great! If you want to go ahead and add them feel free! I will DM you the CT web editor credentials.

**Comment by dipamsen** [comment]
I have added the promise code examples.

**Comment by shiffman** [comment]
Thank you @dipamsen! looks like there is a minor JSON error.
```
FAIL content-testing/format.test.js
  ● Check if JSON file content fits format › Checking video format for ./content/videos/js/particle-system-with-array-functions/index.json

    expect(received).not.toThrowError()

    Error name:    "UnexpectedPropertyError"
    Error message: "Property 'icon' in codeExamples object isn't expected."

          27 |   for (let property in object) {
          28 |     if (reference.properties[property] === undefined) {
        > 2[9](https://github.com/CodingTrain/thecodingtrain.com/runs/8077588033?check_suite_focus=true#step:5:10) |       throw new UnexpectedPropertyError(property, name);
             |             ^
          30 |     } else {
          31 |       const referenceType = reference.properties[property].type;
          32 |
```

**Comment by dipamsen** [comment]
This should be fixed now.

**Comment by shiffman** [comment]
Thank you @dipamsen!

**Pull request merged**
