### PR TITLE
New topic select

### PR DESCRIPTION
**Pull request by bravomartin**
This PR replaces the topic filter with a new top selector with search functionality, making it easier to navigate through the topics.

demo

### CODE REVIEW

**Comment by shiffman** [comment]
ooooh, this is exciting!

**Review by runemadsen — CHANGES_REQUESTED** [review]
This is excellent @bravomartin! I just fixed the build, so the preview is now working. I think we also need to change the language selector, so we have the two selectors side by side. If you can do that, I vote for merge afterwards!

**Comment by bravomartin** [comment]
Added the filter-select to languages. please take another look and approve / merge if it works for you

**Comment by runemadsen** [comment]
This looks great to me! @shiffman feel free to merge if you don't have any input. As far as the lowercase/uppercase problem, I do agree that a `Processing` and `process` topic should lead to the same filter. I think we could fix this by adding notes to the content tests or just lowercasing things in the URL.

**Review by shiffman — APPROVED** [review]
Woohoo!

**Comment by shiffman** [comment]
> This looks great to me! @shiffman feel free to merge if you don't have any input. As far as the lowercase/uppercase problem, I do agree that a `Processing` and `process` topic should lead to the same filter. I think we could fix this by adding notes to the content tests or just lowercasing things in the URL.

Would it be crazy to do both? Merging!

**Pull request merged**
