### PR TITLE
Ported CC 76 10Print

### PR DESCRIPTION
**Pull request by DenisovichDev**
This PR Ports coding challenge 76: 10Print

That was a lot of contributions. Good news is almost all of the contributions are still available, only two were no longer available.
I don't know how I did it, but it's finally done.

### CODE REVIEW

**Comment by shiffman** [comment]
Oh my! So many contributions!

**Comment by DenisovichDev** [comment]
@shiffman It's the most I think. This is where vim comes handy!

**Comment by shiffman** [comment]
This is an absolutely heroic effort! @allcontributors add @DenisovichDev for content

**Comment by shiffman** [comment]
> @shiffman
> 
> This project's configuration file has malformed JSON: .all-contributorsrc. Error:: Unexpected token ] in JSON at position 1112

@klinegareth can you take a look at the above error ⬆️

**Comment by klinegareth** [comment]
@allcontributors add @DenisovichDev for content

**Comment by klinegareth** [comment]
> > @shiffman
> > This project's configuration file has malformed JSON: .all-contributorsrc. Error:: Unexpected token ] in JSON at position 1112
> 
> @klinegareth can you take a look at the above error arrow_up

This should be fixed with #451!

**Comment by klinegareth** [comment]
Trying this again,  @allcontributors add @DenisovichDev for content

**Comment by DenisovichDev** [comment]
@klinegareth I'm not sure if this is why it's not working, but I'm already in content. And probably twice in `README.md` accidentally

**Comment by shiffman** [comment]
Thanks again for working on this one @DenisovichDev!!

**Pull request merged**
