### PR TITLE
Showcase Submission for challenges/55-mathematical-rose-patterns

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Panna for your contribution! A member of the Coding Train team will review it shortly.

* [Neon Lights](https://editor.p5js.org/tamaki.komatsuzaki/sketches/9_Y2gNkAK)
* Panna

preview image

### CODE REVIEW

**Comment by panna3** [comment]
I submitted this yesterday and got deleted.

**Comment by shiffman** [comment]
It looks like there were some issues with recent builds. I just triggered a manual "clear cache and deploy" production build which should take ~5 minutes. @fturmel happy to add you to the netlify team! It looks like I need an email address, feel free to DM / tag me on Discord!

**Comment by fturmel** [comment]
Should be all set!

CleanShot 2024-05-04 at 08 19 47@2x

**Comment by panna3** [comment]
Thank you.

**Pull request closed without merging**
