### PR TITLE
Update font files to the new files

### PR DESCRIPTION
**Pull request by bravomartin**
This PR updates the font files used in the website and adds Oblique variants for the eventual case that italics are used.

### CODE REVIEW

**Review by shiffman — COMMENTED** [review]
Thank you @bravomartin! I haven't reviewed every page but I noticed that the font looks different on the Getting Started Guide.

Current site:
Screen Shot 2022-09-20 at 5 18 36 PM

Deploy preview with new fonts:
Screen Shot 2022-09-20 at 5 18 40 PM

Let me know how best to proceed!

**Comment by bravomartin** [comment]
Good catch @shiffman. Will update the font!  The bubbly font has three variants and I picked the wrong one.

**Comment by bravomartin** [comment]
Fonts updated! @shiffman

**Comment by shiffman** [comment]
Looks great!! Thank you @bravomartin!

**Pull request merged**
