### PR TITLE
Showcase Submission for sound/8-microphone-input

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Peyman Majidi for your contribution! A member of the Coding Train team will review it shortly.

* [Voice Pong! Pong game control via voice input](https://editor.p5js.org/)
* [Peyman Majidi](https://www.youtube.com/@peymanx/)

preview image

### CODE REVIEW

**Comment by shiffman** [comment]
@peymanmajidi the screenshot looks so cool! I think maybe the link is a mistake? it's just the web editor, can you double check and provide the URL for the project?

**Comment by shiffman** [comment]
(Adding a new label "awaiting update" for submissions that need attention before merged, open to a better term!)

**Comment by kfahn22** [comment]
I have added the link

**Comment by shiffman** [comment]
Thank you @kfahn22!

**Pull request merged**
