### PR TITLE
Adding 103-Fire-Effect

### PR DESCRIPTION
**Pull request by borntofrappe**
Adds challenge 103 - Fire Effect (although the same project is labeled as "Flames" in some places)

I've also modified `index.json`, comparing the file with other challenges and specifically the file from challenge 102 - 2D Water Ripples:

- `"languages"`: added processing since the challenge includes a Processing version
- `"codeExamples"`: included the links for the p5js web editor and connected code in a single entry
- `"groupLinks"`: added descriptions for the references and videos associated with the challenge

Finally, I've updated one of the contributions to link to the source code in the `"source"` field.

### CODE REVIEW

**Comment by borntofrappe** [comment]
Let me know if you need more changes @kfahn22. 

I saw you modified the `index.json` file in other similar pull requests and I will follow your lead.

**Comment by kfahn22** [comment]
Thank you for porting a challenge page!!  If you wanted to choose a couple of key topics (the entire list was auto-generated) and add icons, that would be great.

**Comment by borntofrappe** [comment]
Similarly to the challenge for the 2D water ripple I've tried to list the steps in the `timestamps` field. Hopefully it's satisfactory.

**Comment by kfahn22** [comment]
Thank you, this looks great!!  Do you want to add any images? If not, I can add later.

**Comment by borntofrappe** [comment]
Should I take a few frames from the video?

**Comment by kfahn22** [comment]
We have been running the code and getting an image using Coding Train Colors.  Here is a collection of the ones I have done, for reference.  I would be happy to create the index image, if you would prefer.
 https://editor.p5js.org/kfahn/collections/aiHkHeT8h

**Comment by borntofrappe** [comment]
The image relative to the demo makes absolute sense. I'm not familiar with the "Coding Train Colors" tool though. If I can learn how to process the image I'm up to it. Whichever way you prefer.

**Comment by borntofrappe** [comment]
Running the demo and clicking "Save Image As..." seems to do the trick.

Simple Particle System

Would that be enough?

**Comment by borntofrappe** [comment]
Oopsie, I got confused with the simple particle system.

fire-effects

**Comment by DenisovichDev** [comment]
Hey @borntofrappe thank you for doing this! You can add one of the images you have shown here to the `image` folder, and add the name of the image file to the `image` attribute of the code example. I'll add an image with coding train colours for `index.png` later on before we merge it

**Comment by kfahn22** [comment]
codingtrain_colors
Here are the Coding train colors.

**Comment by kfahn22** [comment]
You would need to add an images folder and then add the code example images to the folder.

**Comment by borntofrappe** [comment]
Thank you for the support @kfahn22 and @DenisovichDev

**Comment by kfahn22** [comment]
If you wanted to look at an example, 174-graphics-applesoft-basic would be a good one.

**Comment by kfahn22** [comment]
Great job!!!

**Comment by kfahn22** [comment]
There is one last optional thing you can add, but this is totally up to you!
  
We have been grabbing screenshots of the showcases.  For example, here is a screenshot of contribution2.  This image would be named contribution2.jpg and added to the showcase folder.  The one thing to be aware of is that there are size limits on the images (800px wide and max 500kb)

Otherwise, I will mark this as approved.  Again, thank you for doing this!!

contribution2

**Comment by borntofrappe** [comment]
If you don't mind to wait a few minutes I'll try my best. Had to leave my pc for a moment.

**Comment by kfahn22** [comment]
You are going great!!  And there is no rush.  Dan is really busy getting ready for the event is appearing at this weekend.

**Comment by shiffman** [comment]
Just wanted to say thank you so much for contributing and @kfahn22 for helping facilitate!! Do we need the `hacktoberfest-accepted` label for it to count? I wonder if we should put that label on all pull requests this month just in case? I'll be back to reviewing things later this weekend and can answer questions ,etc!

**Comment by DenisovichDev** [comment]
Yes I think that would be wise too. Have great time at the event this weekend!

**Comment by borntofrappe** [comment]
Unfortunately the fourth contribution doesn't have a live demo. Let me know if the other are sufficient 👍 

Thanks again to everyone :)

**Comment by DenisovichDev** [comment]
Thank you so much @borntofrappe

**Comment by kfahn22** [comment]
Yes, it is not possible to get an image for all the showcases.  Thank you so much for doing this!!

**Review by kfahn22 — APPROVED** [review]
This looks great!

**Comment by dipamsen** [comment]
@borntofrappe Thanks for the contributions!

@shiffman 

> Do we need the `hacktoberfest-accepted` label for it to count? I wonder if we should put that label on all pull requests this month just in case? I'll be back to reviewing things later this weekend and can answer questions ,etc!

For a PR to be accepted to hacktoberfest, _any one_ of the following should be true:
- The PR must be merged; or
- The PR should have a `hacktoberfest-accepted` label; or
- The PR must have an overall approving review.

i.e. The label is not really required to count for hacktoberfest, but it is an easy way to quickly 'accept' the PR, without actually merging it. So, I think we can put the label on all PRs to prevent the contributors from waiting for the PR to be merged to the repo.

**Comment by borntofrappe** [comment]
I've removed the unnecessary fields as per #640 

There was also a URL missing from one of the videos, apologies.

**Comment by shiffman** [comment]
@dipamsen ah! thank you for the clarification! Good to know we don't need the label so if we forget it's not the end of the world!

**Comment by shiffman** [comment]
This is so fantastic, great work @borntofrappe, I am so grateful for your contribution!

@kfahn22 if you want to work your magic and make a main thumbnail image for this one (and #635) in a separate pull request feel free!

**Pull request merged**
