### PR TITLE
Add canContribute property to NOC track

### LINKED ISSUE #390: NOC index.json canContribute field
I just happened across this by chance b/c of some miss-placed particle system contributions-- the index.json files do not have the canContribute field and the contributions are missing on the website.  I just did a very unscientific random look at the index.json files for NOC and one had the canContribute field but out all the others did not.

### PR DESCRIPTION
**Pull request by dipamsen**
Fixes #390 

- Added canContribute property to videos
- Removed extra showcase
- Added code examples and references to Perlin Noise section

(Due to some reason, I forgot to create a branch and commited to main directly.)

### CODE REVIEW

**Comment by shiffman** [comment]
@dipamsen if you merge this with the latest main, the checks should then pass.

**Comment by dipamsen** [comment]
Looks like it is unable to find the perlin noise videos? (I changed the folder names in these to make it concise)

image

Locally, I got this error once, but it was fixed after running `clean` once. Also, all the tests are passing.

**Comment by shiffman** [comment]
I can confirm the tests pass and the build works locally, must be a caching issue or something on netlify's end. I just triggered a "force clear cache and rebuild". Let's see what happens but I can also go ahead and just force a merge.

**Comment by shiffman** [comment]
Looks all good now!

**Pull request merged**
