### PR TITLE
Quad tree

### PR DESCRIPTION
**Pull request by kfahn22**
This is ready for review.

### CODE REVIEW

**Comment by shiffman** [comment]
Hey! This is terrific! I would use an image that shows the lines of the quadtree itself as that represents the topic better than just the dots. Something along the lines of:

image

Let me know if you'd like to add it or if you prefer I merge and update the image afterwards.

**Comment by kfahn22** [comment]
For the index image?

**Comment by kfahn22** [comment]
quad
Is this OK?

**Comment by shiffman** [comment]
Looks great!

**Pull request merged**
