### PR TITLE
fixed position of alert box

### PR DESCRIPTION
**Pull request by laurie60**
This solves the issue in issue #772.

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @laurie60! Congratulations on your first open source contribution! I am so thrilled to be that place for you! 

The issue is fixed when the button is on the line below the rest of the tabs. But now it looks like it is cutoff on a page where it not pushed to the next line!

Screen Shot 2022-11-24 at 10 04 22 AM

I wonder, is there a way it can detect where it is on the page? Aligned right or left?

Don't worry, I want to make sure we get this merged, I'll look into this too!

**Comment by shiffman** [comment]
@all-contributors  add @laurie60 for code!

**Comment by laurie60** [comment]
> Hi @laurie60! Congratulations on your first open source contribution! I am so thrilled to be that place for you!
> 
> The issue is fixed when the button is on the line below the rest of the tabs. But now it looks like it is cutoff on a page where it not pushed to the next line!
> 
> Screen Shot 2022-11-24 at 10 04 22 AM
> 
> I wonder, is there a way it can detect where it is on the page? Aligned right or left?
> 
> Don't worry, I want to make sure we get this merged, I'll look into this too!

Thank you! Oh flip, sorry I didn't notice that! One way I can think of solving this would be to use the screen width, as the copied button is only able to fit on the same line (where there are >= 5 tabs in the list) on quite wide screens.

But if there is a way to know the position of the button on the screen would be much more flexible.

**Comment by dipamsen** [comment]
@laurie60 One possible solution could be to use a `ref` compare the top offsets (`elt.offsetTop`) of the button to check whether the button is on the same line or on the next line. 

From my experiments I found that when the button is on the right, the top offset is ~800, and when it is below on the left, the offset is ~850, across various zoom levels (that is on large screens, > 1180px. For medium screens, > 900px, this range becomes 850-900). 

If you have some other approach, please feel free to go your own way!

**Comment by laurie60** [comment]
Thanks for the suggestion @dipamsen, I wasn't familiar with that concept, so I wouldn't have thought of it on my own. I implemented the useRef idea in the last commit, I think it is working as we want it to now!

**Comment by shiffman** [comment]
Incredible! I can confirm it's working. Merging! Congratulations @laurie60 on your first open source contribution! ❤️

**Pull request merged**
