### PR TITLE
Showcase Submission for 124-flocking-simulation

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Sergey Alyaev for your contribution! A member of the Coding Train team will review it shortly.

* [A flock of LEGO fire helicopters that my son dreams of assembling](https://www.youtube.com/watch?v=roD93qUTQ7o)
* [Sergey Alyaev](https://github.com/alin256)

preview image

### CODE REVIEW

**Comment by alin256** [comment]
@kfahn22 what are the rules for getting the **[hacktoberfest-accepted]** label? I just woke up and wonder what I am missing out ;)

**Comment by kfahn22** [comment]
I believe you need to submit the showcase through your GitHub account instead of using the interface on the Coding Train website.

**Comment by alin256** [comment]
@kfahn22, I am resubmitting from my account; see #646. Please close this one. 

Sorry for the inconvenience :)

**Comment by kfahn22** [comment]
No problem at all.  I love the idea of flocking LEGO helicopters!

**Comment by shiffman** [comment]
FYI I am absolutely fine with pull requests submitted from the website being accepted for Hacktoberfest! (Assuming they are not spam and all the other usual caveats.) It just should be noted that if a contributor does not enter their email into the form or if they do not have a GitHub account tied to their email, then the pull request commits are assigned to @ch00ooch00oo. Come to think of it, the pull request always comes from @ch00ooch00oo so maybe it won't work even if the commits are from a different user. I'm not sure! Safest bet is to submit via GitHub directly for sure!

**Pull request closed without merging**
