### PR TITLE
Adding ml5 track

### PR DESCRIPTION
**Pull request by kfahn22**
Adding ml5 track. 

Notes:
--   I have only added a couple of code example images. 
--   While I have tried to get images for the contributions,  I have not added images for those that needed webcam data.  (There was also one that only worked in Windows and I have a Mac.)

Please let me know if I need to make corrections!

### CODE REVIEW

**Comment by shiffman** [comment]
@kfahn22 is this ready for review and merge? Let me know, @klinegareth and I are here to answer any questions! Thank you so much for working on this!

**Comment by kfahn22** [comment]
Yes, it is ready for review.  Please let me know if there are any corrections that need to be made.

**Comment by dipamsen** [comment]
@kfahn22
Since this is a main track, the videos need to be organised into chapters. The required file structure should be

```
content/videos
|_ ml5

  |_ 0-introduction
     |_ introduction
       |_ index.json

  |_ 1-classification
     |_ 1-image-classification
       |_ index.json
     |_ 2-webcam-classification
       |_ index.json
     |_ 3-object-detection
       |_ index.json

  |_ 2-transfer-learning
     |_ 1-transfer-learning
       |_ index.json

  |_ 3-feature-extractor
     |_ 1-feature-extractor-classification
       |_ index.json
     |_ 2-feature-extractor-regression
       |_ index.json
//...
```

All the files for a video - `index.json`, `showcase` and `images` will be present in the video directory.

------

The track's `index.json` file, which is used to identify a track is missing. This needs to be added in `content/tracks/main-tracks/beginners-guide-to-machine-learning-with-ml5/index.json`

```jsonc
{
  "title": "Beginner's Guide to Machine Learning in JavaScript",
  "date": "2018-07-31",
  "description": "<add track description>",
  "chapters": [
    {
      "title": "Chapter Name",
      "videos": ["ml5/0-introduction/introduction"]
    },
    {
      "title": "Chapter Name",
      "videos": ["ml5/1-classification/1-image-classification", "ml5/1-classification/2-webcam-classification", "ml5/1-classification/3-object-detection"]
    },
    // ...
  ]
}
```

**Comment by kfahn22** [comment]
Thanks!

**Comment by kfahn22** [comment]
I reorganized the ml track into chapter folders .  (I assumed that the folders  would just be renamed but instead the files were duplicated so I had to delete originals, which is why  it looks like I have made more changes that I actually made.)   I have not added the track json file as that appears to cause the pull request to fail.

**Comment by kfahn22** [comment]
Chapter 8 folder name has a typo--network is miss-spelled.  Sorry, I can't figure out how do fix it on github (would love to learn how to do it).

**Comment by dipamsen** [comment]
I tried to fix the typos, but I don't seem to have the commit access; (though, weirdly enough I was able to make a couple of changes through GitHub, but I can't upload/delete files).

The changes needed are
- rename `content/videos/ml5/8-convolutional-neural-netowrk/ → /8-convolutional-neural-network/`
- rename `content/videos/ml5/8-convolutional-neural-network/4-image-classification./ → /4-image-classification/`

**Comment by shiffman** [comment]
Looks like the checks are passing now! @kfahn22 is this ready for a review and merge?

**Comment by kfahn22** [comment]
I believe so.  Let me know if I need to make changes.

**Pull request merged**
