### PR TITLE
Showcase Submission for 134-heart-curve challenge

### PR DESCRIPTION
**Pull request by M0nica**
Adding an additional example to the heart Curve Challenge.

### CODE REVIEW

**Comment by fturmel** [comment]
@M0nica nice!

If you want your contribution to appear chronologically in the new [showcase](https://thecodingtrain.com/showcase) section, you can also add a "submittedOn" property in the format `yyyy-mm-dd`.

**Comment by M0nica** [comment]
> @M0nica nice!
> 
> If you want your contribution to appear chronologically on the new [showcase](https://thecodingtrain.com/showcase) section, you can also add a "submittedOn" property in the format `yyyy-mm-dd`.

Great, thank you for the suggestion and thanks @shiffman for updating to include the date!

**Comment by fturmel** [comment]
@shiffman no trailing commas in JSON! This last commit should fix it

**Comment by shiffman** [comment]
@fturmel yes! I found this at the same time! I finally caved and worked with the file locally which made it easy for me to see.

**Pull request merged**
