### PR TITLE
Adding 58 3d earthquake data visualization

### PR DESCRIPTION
**Pull request by borntofrappe**
There is a related challenge, but it hasn't been ported yet. Once it is `index.json` should be updated in at least two instances (assuming the challenge is ported as '57-mapping-earthquake-data'):

1. the `relatedChallenges` field

   ```diff
   "relatedChallenges": [],
   +"relatedChallenges": ["57-mapping-earthquake-data"],
   ```

2. the reference section devoted to `Videos`

   ```diff
   -"icon": "🎥",
   "title": "Earthquake Data Visualization",
   -"url": "https://youtu.be/ZiYdOwOrGyc",

   +"icon": "🚂",
   "title": "Earthquake Data Visualization",
   +"url": "/challenges/57-mapping-earthquake-data",
   ```

### CODE REVIEW

**Comment by kfahn22** [comment]
Thank you, this looks great!

**Comment by kfahn22** [comment]
We are starting to add links to the Livestream archive.  Here is the one for 3D earthquake data visualization if you would like to add it to the json.
 {
          "icon": "🎥",
          "title": "Livestream Archive",
          "url": "https://youtu.be/L1nHni9HMBw",
          "description": "Livestream with 3D Earthquake Data Visualization and Steering Behaviors"
 }

**Comment by borntofrappe** [comment]
I've linked to the archive 👍

**Comment by shiffman** [comment]
Wonderful, thank you!!

**Pull request merged**
