### PR TITLE
Adding 78 simple particle system

### PR DESCRIPTION
**Pull request by borntofrappe**
Adds challenge 78 following the [Maintaining the website guide](https://thecodingtrain.com/guides/maintain-website-guide).

I've also modified `index.json`, comparing the file with other challenges and updating a few fields:

- `"languages"`: added processing since the challenge includes a Processing version
- `"codeExamples"`: included the links for the p5js web editor and connected code in a single entry
- `"groupLinks"`: added descriptions for the references and videos associated with the challenge

### CODE REVIEW

**Comment by kfahn22** [comment]
I wanted to add that If you try running a showcase and you get a 404, it can be deleted.

**Comment by borntofrappe** [comment]
@kfahn22 I was actually going to ask that right now :) 

Thank you in advance, quite literally.

**Comment by kfahn22** [comment]
Thank so much for adding this!  It looks great!!

**Review by kfahn22 — APPROVED** [review]
This looks great!

**Comment by borntofrappe** [comment]
I've removed the unnecessary fields as per #640

**Comment by shiffman** [comment]
Woohoo, another wonderful contribution, thank you @borntofrappe and @kfahn22 for reviewing!!

**Pull request merged**
