### PR TITLE
adds favicon

### LINKED ISSUE #444: Favicon is missing
I have noticed that there is an absence of a favicon in the website. I'm not sure if there is a plan for that, but still I thought I should open this issue.

### PR DESCRIPTION
**Pull request by fdoflorenzano**
I followed [this setup](https://css-tricks.com/how-to-favicon-in-2021/), and I used [realfavicongenerator](https://realfavicongenerator.net/) to generate other versions from the SVG base.

I went with the zoomed-upright grey background one. The not zoomed one was difficult to see in a small icon, the dark and orange were a bit much to my taste. The one select also I felt reflected the whole site a bit better :) 

Also you can see a test by the same website over the preview: https://realfavicongenerator.net/favicon_checker?protocol=https&site=deploy-preview-478--codingtrain.netlify.app%2F#.YwPwh_HMIqs

This resolves #444

### CODE REVIEW

**Review by runemadsen — APPROVED** [review]

**Comment by shiffman** [comment]
Hi @jasontheillustrator! Any thoughts on this favicon before merging? Thank you @fdoflorenzano for adding this!!

**Comment by jasontheillustrator** [comment]
I'm not sure that favicon is working too well. At the small size, you cant see his facial expression so it just ends up looking like 2 pink boxes with one getting cut off. I created a few other options sized for the small favicon size. Take a look and let me know what you think.
CodingTrain-Favicon-CT
CodingTrain-Favicon-Rainbow
CodingTrain-Favicon-Train-Purple
CodingTrain-Favicon-TrainSolid

**Review by shiffman — COMMENTED** [review]
@runemadsen and @fdoflorenzano any preference from the images suggested by @jasontheillustrator?

**Comment by runemadsen** [comment]
Thanks for this @jasontheillustrator! They're all lovely :) I prefer the rainbow, but I could go with any of them. Should we do rainbow? @shiffman?

**Comment by shiffman** [comment]
Rainbow works for me! What formats do we need it in?

**Comment by jasontheillustrator** [comment]
I uploaded PNG files which is common for Favicons, but if you need a different format, just let me know.

**Comment by shiffman** [comment]
Hi @fdoflorenzano, the designs from @jasontheillustrator are here!

https://drive.google.com/drive/folders/1S0MWBwUiOBrHjsgBdNNAbnB7h3mottdt?usp=sharing

Do you want to replace the semi-colon with the rainbow in this pull request or shall we give it a try?

**Comment by fdoflorenzano** [comment]
> Do you want to replace the semi-colon with the rainbow in this pull request or shall we give it a try?

Sure thing! I'll get into it!

**Comment by fdoflorenzano** [comment]
@jasontheillustrator Could you add an SVG version of the rainbow?

**Comment by jasontheillustrator** [comment]
I just updated the folder.

**Comment by fdoflorenzano** [comment]
Preview updated! https://deploy-preview-478--codingtrain.netlify.app/
@jasontheillustrator @shiffman @runemadsen

**Comment by jasontheillustrator** [comment]
Looks good!

**Comment by shiffman** [comment]
Fantastic, thank you @jasontheillustrator and @fdoflorenzano!

**Pull request merged**
