### PR TITLE
Noc angles adding code example images and showcase images

### PR DESCRIPTION
**Pull request by kfahn22**
This is 3.1-3.3

Folder for 3.1 Had a duplicate of a contribution from folder 1.3 so was deleted.  

Also deleted another contribution that wasn't working.

### CODE REVIEW

**Comment by shiffman** [comment]
Weird I'm not sure why, but the wrong image is showing up in the preview! @klinegareth can you take a look, do you see anything I'm missing?

Screen Shot 2022-08-08 at 9 20 16 PM

**Comment by dipamsen** [comment]
> Weird I'm not sure why, but the wrong image is showing up in the preview! @klinegareth can you take a look, do you see anything I'm missing?
> 
> https://deploy-preview-433--codingtrain.netlify.app/tracks/the-nature-of-code-2/noc/3-angles/1-angles-and-rotation

@shiffman Globally on all main and side tracks, the contribution images are not working. I opened #434 regarding this.

**Review by shiffman — CHANGES_REQUESTED** [review]
Let's sort out why the image is working before merging?

**Comment by kfahn22** [comment]
I only did a pull request so we could do a check to see if the new image was displayed.  I agree -- no point in merging until this is resolved.

**Review by shiffman — APPROVED** [review]

**Comment by shiffman** [comment]
Going to merge this with #438 and all should we well!

**Pull request merged**
