### PR TITLE
Adding 45 p5js firebase drawings

### PR DESCRIPTION
**Pull request by borntofrappe**
- adds challenge files
- updates contribution
- includes thumbnail image
- updates challenge details

I had to be a tad creative with the images. I hope they are satisfctory.
At least they might make you chuckle :)

### CODE REVIEW

**Comment by kfahn22** [comment]
Thank you!!  I personally love your image!  Here are some relatedChallenges to add:

"relatedChallenges": ["122-quick-draw","130-drawing-with-fourier-transform-and-epicycles"]

**Comment by shiffman** [comment]
That drawing is incredible @borntofrappe! @jasontheillustrator you have got to take a look!

image

**Comment by shiffman** [comment]
I'll wait to merge in case you want to add the related challenges suggested by @kfahn22!

**Comment by borntofrappe** [comment]
Thanks for the kind words @shiffman 😄

**Pull request merged**
