### PR TITLE
Voronoi game of life submission

### PR DESCRIPTION
**Pull request by okg21**
Voronoi game of life showcase submission

### CODE REVIEW

**Comment by shiffman** [comment]
Ah, whoops, I think this was already merged in #1622, can you confirm?

**Comment by okg21** [comment]
Hey, yes, the only difference is this one goes directly to a demo. If it is OK, I prefer this one. But it's OK anyway. Thank you.

**Comment by shiffman** [comment]
> Hey, yes, the only difference is this one goes directly to a demo. If it is OK, I prefer this one. But it's OK anyway. Thank you.

Ah, that makes sense! Since I already merged #1622, would you like to adjust this branch (or open a new pull request) that changes the link in the file that is now in main?

**Comment by okg21** [comment]
> > Hey, yes, the only difference is this one goes directly to a demo. If it is OK, I prefer this one. But it's OK anyway. Thank you.
> 
> Ah, that makes sense! Since I already merged #1622, would you like to adjust this branch (or open a new pull request) that changes the link in the file that is now in main?
Thanks, I will open a pull request that updates the link.

**Comment by fturmel** [comment]
@okg21 Hope you don't mind, I opened a PR to close this issue. See #1665

**Pull request closed without merging**
