### PR TITLE
Showcase Submission for 122-quick-draw

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Zelf for your contribution! A member of the Coding Train team will review it shortly.

* [Random Painter Half Frame](https://editor.p5js.org/thezelf/sketches/CVKRvh4hO)
* Zelf

preview image

### CODE REVIEW

**Comment by shiffman** [comment]
This is a lovely sketch! I wonder if we could find a better spot for it since it doesn't related to quick, draw? Maybe we could move it to one of the intro p5 videos?

**Comment by fturmel** [comment]
Some suggestions:
https://thecodingtrain.com/tracks/code-programming-with-p5-js/code/2-variables/1-mouseX-mouseY
https://thecodingtrain.com/challenges/45-p5js-firebase-drawings

**Comment by fturmel** [comment]
@shiffman What do you think of moving the contribution to the p5js mouse position video and merge? The PR has been sitting here for a while now.

https://thecodingtrain.com/tracks/code-programming-with-p5-js/code/2-variables/1-mouseX-mouseY

**Comment by shiffman** [comment]
> @shiffman What do you think of moving the contribution to the p5js mouse position video and merge? The PR has been sitting here for a while now.
> 
> https://thecodingtrain.com/tracks/code-programming-with-p5-js/code/2-variables/1-mouseX-mouseY

Yes, let's do it!

**Comment by fturmel** [comment]
Done!

**Pull request merged**
