### PR TITLE
Adding 32 agario

### PR DESCRIPTION
**Pull request by borntofrappe**
A few notes on the pull request:

- the second demo in the `"codeExamples"` field is neither connected to p5 or processing, so I've used the label `"other"`

  ```json
  {
    "title": "Agar.io - Part 2 (Networking with Socket.IO and Node.js)",
    "description": "This project sets up a server so that visitors are able to compete in a version of the game Agar.io.",
    "urls": {
      "other": "https://github.com/CodingTrain/Coding-Challenges/tree/main/032.2_agar.io_sockets/Node"
    }
  }
  ```

- there is no live demo for the second example (unless you set up the node server I presume), so I've added a single image for the both with `index.jpg`

- there are two live streams connected to the challenge, and I've added the number to distinguish the two

  ```json
  {
      "icon": "🔴",
      "title": "Livestream Archive #55",
      "url": "https://youtu.be/eOii4P7WYbY",
      "description": "Livestream with Flappy Bird and Agar.io clones."
  },
  {
      "icon": "🔴",
      "title": "Livestream Archive #58",
      "url": "https://youtu.be/_cDPN2Ief6Q",
      "description": "Livestream with networking Agar.io and the history of p5.js/Processing."
  }
  ```

Let me know if you have suggestions, improvements on the current structure

### CODE REVIEW

**Comment by kfahn22** [comment]
Thank you so much for this!! I like the way that you have added the Livestream # in the title.  ( I have been putting  it in the description).  I am wondering whether it makes sense to have the following format, especially if there are no other videos that are being  linked to:

{
  "title": "Livestream Archive",
  "links": [
    {
      "icon": "🔴",
      "title": "Livestream #157",
      "url": "https://youtu.be/jSzmac4Rri8",
      "description": "Livestream with Binary Numbers & Bit Shifting"
    }
  ]
}
@shiffman What do you think?  And if there are other videos, would one video section be best?

**Comment by dipamsen** [comment]
@kfahn22 I agree! I think this structure is better for organisation when the challenge spans multiple livestreams.

**Comment by kfahn22** [comment]
I am not sure if there are any others, but I think these two challenges would be good for related challenges if you want to update.  Again, thank you for all the effort you have put in to porting challenges!!

"relatedChallenges": ["36-blobby", "69-evolutionary-steering-behaviors"]

**Comment by borntofrappe** [comment]
I've included the suggested changes @kfahn22 
And thank you for the supportive message :)

**Comment by shiffman** [comment]
Yes, this all sounds great to me, yay!!!

**Pull request merged**
