### PR TITLE
Create showcase-contibitution - shapes and line

### PR DESCRIPTION
**Pull request by Mehakdoracode**
Adding my first showcase edition and also my first code .

### CODE REVIEW

**Comment by kfahn22** [comment]
Congratulations on your first pull request!!  Which video do you want this showcase to be added to?  Do you want to add an image for your showcase?

**Comment by kfahn22** [comment]
Hi @Mehakdoracode! 

This is something I didn't realize the first time I added a showcase to a track video, but all showcases must be associated with a video.  So, for example, if you wanted to submit a showcase to "code/1-intro/3-shapes-drawing" you would go to that folder, add a new folder named "showcase" and move your contribution to that folder.  After this is done, the path should would be "content/videos/code/1-intro/3-shapes-drawing/showcase/contribution1.json".  (It doesn't have to be named contribution1.)  The process is similar if you want your showcase to be associated with a different video.  If you would like help either moving your showcase or adding an image, please let me know and I can assist you.  Thanks again for contributing to the Coding Train website!

**Comment by Mehakdoracode** [comment]
Okay I don't know how to do that I'll try again

**Comment by dipamsen** [comment]
@Mehakdoracode Hey! If you are having some trouble creating the pull request, you can use the submission form on the website instead: https://thecodingtrain.com/submit
Or if you want, a community member can help you move the files to the correct locations.

**Comment by Mehakdoracode** [comment]
I don't how to pull request and submit the file

**Comment by kfahn22** [comment]
Hi @Mehakdoracode!  Here are more detailed steps on adding a showcase to a track on Github (@shiffman went over how to find the folder yesterday during his livestream) if you want to try to edit your pull request.  I can also move your showcase to the right place or, if you would prefer,  or you can add directly on the website using the interface.

-click on the folder named "content"
-click on the folder named  "videos"
-click on the folder named "code" (if that is the tutorial series you want to add to)
-click on the folder named "1-intro"
-click on the folder named "3-shapes-draw"
-click on addfile (on right)
Screenshot 2023-08-24 at 9 27 29 AM
You will need to write "showcase" and then contribution1.json.
Screenshot 2023-08-24 at 9 27 56 AM
Screenshot 2023-08-24 at 9 28 35 AM

A couple of other notes:  in the url field just list the url; 
The date should be formatted like this:  2022-09-29 or 2023-02-03T12:27:37.854Z

**Comment by Mehakdoracode** [comment]
Awesome, thank you so much!

**Comment by shiffman** [comment]
Great work @Mehakdoracode congrats on your first pull request! I updated the author url, we should probably check for valid urls in the tests, what do you think @dipamsen? Merging!!

**Comment by shiffman** [comment]
(waiting for tests to pass first..)

**Comment by fturmel** [comment]
@shiffman this was not ready to merge yet, the contribution was created in a directory at the root of the repo, the submittedOn date is in the wrong format, no preview image, etc.

**Comment by shiffman** [comment]
Ooops, I didn't look closely enough, thanks for helping catch my mistake @fturmel! I opened #1186 which reverts this and perhaps we can correct there?

**Comment by fturmel** [comment]
I'd say let's re-open #1185 instead and just fix the `submittedOn` date.

**Pull request merged**
