### PR TITLE
Adding Discord Bots side-track

### PR DESCRIPTION
**Pull request by SilvestriStefano**
another part of issue #965

### CODE REVIEW

**Comment by shiffman** [comment]
Thank you so much for doing this! I haven't managed to redo these tutorials (though it is on my list!) but a lot of the content no longer works with newer versions of the library, if we include this side track is there a way to  note this clearly on the website or would it be best not to include this side track until I've had a chance to redo the videos?

Thank you so so much for taking the time to work on this!

**Comment by SilvestriStefano** [comment]
I see... well for starters I can add a note about it in the description of the track. 
Another solution could be creating a sort of _Archive_ (not necessarily the name) section that contains all the tracks that are now outdated. For example, the old processing tutorial can go in there. 🤷‍♂️

**Comment by shiffman** [comment]
Guess what! I recorded the first three videos in the new Discord Bot Side track! So that your commits can be merged, I think we should adapt this branch with the new videos when they are ready!

**Comment by shiffman** [comment]
@SilvestriStefano the first new discord bot video is coming out tomorrow! (or soon thereafter). The info for the video is here: https://github.com/CodingTrain/Discord-Bot-Examples/wiki/Workflow:-Terminal,-Shell,-Node,-VSCode 

Some options are:

+ Close this pull request (with a giant internet hug and thank you from me!)
+ Adapt your branch, removing outdated videos, and bring in the new videos here
+ Consider a new "archive" section of website for older videos like this one?

Tagging in @dipamsen who may have some ideas! Apologies for the late notice, regardless, I would like to add the new video to the site later today or tomorrow!

**Comment by dipamsen** [comment]
If we want to keep these videos, we could for now mark the track as "Archived" (in the title) and display it at the end of the track listing, with a note in the description stating that there is a newer version of the track.

**Comment by supercrafter100** [comment]
Perhaps a future idea for the site itself is a dedicated "archived" label for tracks? To make it also visually appear archived

**Comment by SilvestriStefano** [comment]
Hello,
I think it is better to just add the new videos (either by adapting this branch or creating a new one). In the future if someone wants to make a discord bot would want to use the up-to-date instructions, no?

If we really want to keep an archive of previous videos/tracks why don't we use the old website (https://codingtrain.github.io/website-archive/) for that?

**Comment by shiffman** [comment]
@allcontributors add @SilvestriStefano for ideas, code, doc

**Comment by shiffman** [comment]
Cleaning up some things today, I think it makes sense to close this and acknowledge the contribution with allcontributors, thank you @SilvestriStefano! Open to other ideas, solutions, if need be!

**Comment by SilvestriStefano** [comment]
thank you @shiffman !

**Pull request closed without merging**
