### PR TITLE
Adding 66-javascript-countdown-timer

### PR DESCRIPTION
**Pull request by borntofrappe**

### CODE REVIEW

**Comment by borntofrappe** [comment]
For `javascript-countdown-timer.jpg` I included a picture of the timer alongside the JavaScript code in the p5 web editor, I hope it's satisfactory. 

Ultimately I created a similar version with a more appropriate aspect ratio for `index.jpg`. Let me know if the image could work for `index.jpg` as well (similarly to #640).

javascript-countdown-timer

Unfortunately the output of the challenge is not visually striking, but there's a lot of knowledge behind that string of text.

**Comment by borntofrappe** [comment]
It's a pleasure @kfahn22 :)

I will undoubtedly use the thumbnail you proposed, but I have one last question: should the image have the same constraints as those for the contributions? 800pixels wide, at most? The weiught is already well below the 500+kb threshold.

**Comment by kfahn22** [comment]
No, the index images do not have the same constraints and ideally should 1280 by 720.

**Comment by shiffman** [comment]
Amazing!!!

**Pull request merged**
