### PR TITLE
Main Track: Working with Data and APIs in JavaScript

### PR DESCRIPTION
**Pull request by dipamsen**
Main Issue: #279

(This PR needs to be merge after the merging of https://github.com/CodingTrain/Intro-to-Data-APIs-JS/pull/67 )

- Using trailer thumbnail for now as cover image
- Removed `source` field from contributions
- Updated references and video links 

image
image
image

Note: Seems like the showcase thumbnails are not working due to some reason. I have not been able to figure out why, I have also tried using lower resolution images but it is not showing up.

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @dipamsen! Thank you for this incredible work! This is ready to merge, yes? Just scanned it over, the only comment I have is maybe to remove the numbering from the titles?

**Comment by dipamsen** [comment]
@shiffman I have removed the video numbers from the titles. This is ready to merge, but I would like to put forward some comments:

1. The showcase thumbnails don't show up. If I have done everything correctly, showcase thumbnails do not seem to work for main tracks. (But again, none of the other main tracks have showcase thumbnails in them, so I am not sure what the issue is here. Feel free to merge this and this can be investigated in a different thread!)
2. Also, https://github.com/CodingTrain/Intro-to-Data-APIs-JS/pull/67 needs to be merged, in order to avoid 404 GitHub links.

**Comment by shiffman** [comment]
@klinegareth this looks good to me, all set to merge? @jasontheillustrator will create a new "track thumbnail" for this but I'll add that to the website separately later this week.

**Comment by klinegareth** [comment]
@shiffman I think it all looks good! Can I go ahead and merge?

**Comment by shiffman** [comment]
Yes! I'll merge now!

**Pull request merged**
