### PR TITLE
Challenge 118 - Mastodon Fractal Tree Bot

### PR DESCRIPTION
**Pull request by fturmel**
Related #1627

This is mostly done, but would appreciate some help wrapping things up and doing QA. There were no chapters for part 1, so I gave it a shot while watching the video.

https://deploy-preview-1670--codingtrain.netlify.app/challenges/118-mastodon-fractal-tree-bot

References from the archived site:
https://github.com/CodingTrain/website-archive/blob/main/_CodingChallenges/118.1-mastodon-fractal-tree.md?plain=1
https://github.com/CodingTrain/website-archive/blob/main/_CodingChallenges/118.2-mastodon-fractal-tree.md?plain=1

**TODO**

- [ ] Add thumbnail image
- [x] Write descriptions for all links
- [ ] QA
- [ ] Update video descriptions on YouTube to fix missing chapters and dead links

### CODE REVIEW

**Comment by dipamsen** [comment]
Might make sense to add this to https://thecodingtrain.com/tracks/mastodon

**Comment by fturmel** [comment]
I removed the link https://mastodon.social/@codingtrain@choochoo.space since it redirects to a dead end (https://choochoo.space/@codingtrain)

**Comment by shiffman** [comment]
All right, I've updated the video descriptions and suggested a thumbnail idea in #1627, happy to merge whenever!

**Comment by shiffman** [comment]
Apologies for missing that this one is good to go!

**Pull request merged**
