### PR TITLE
Showcase Submission for challenges/177-soft-body-character

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you Panna for your contribution! A member of the Coding Train team will review it shortly.

* [Colorful Spring Ball](https://editor.p5js.org/tamaki.komatsuzaki/sketches/HmGn9Z-t4)
* Panna

preview image

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @panna3! These are wonderful! I might suggest combining #1209 and #1210 into one submission as they are very similar! Maybe you might like to add a button or mouse clock to change between the ring and the underlying lines? I can help with that if you like!! ✨

**Comment by panna3** [comment]
Yes, I'll try adding buttons.

**Comment by panna3** [comment]
Hello Shiffman,

I tried to fix my code but I cannot pass the number of points to another
class panna in setup function.
It just gets the default number. I want to increase the number of points
when its Ring.
setup function is not called when I press the button but if i
write pannasan = new Panna(width/2,height/2,25);
in draw function it makes a lot of panna.If i don't write that code in
setup I cannot call pannasan.show(); in draw function.
Could I have some help?

https://editor.p5js.org/tamaki.komatsuzaki/sketches/HmGn9Z-t4

Tamaki Komatsuzaki

**Comment by panna3** [comment]
Hi, I figured it out. I have fixed the code. Could you upload this one to the showcase instead of the other one? I see the other one is added.

**Comment by panna3** [comment]
never mind. I changed the code of the other one that is already added to showcase.

**Comment by shiffman** [comment]
Thanks @panna3 for updating, this is a wonderful project! I'll close this issue since, let me know if you have any more questions or if I can help in any other way!

**Pull request closed without merging**
