### PR TITLE
Showcase Submission for 16-l-system-fractal-trees

### PR DESCRIPTION
**Pull request by ch00ooch00oo**
Thank you kaykay for your contribution! A member of the Coding Train team will review it shortly.

* [sea fan(L-System) & sea slug(ASCII Image)](https://youtu.be/aY41RhS-6LE)
* kaykay

preview image

### CODE REVIEW

**Comment by dipamsen** [comment]
Somehow this worked when I entered the exact same information?

**Comment by dipamsen** [comment]
@kfahn22 btw the label is not required in these PRs (unless @ch00ooch00oo bot wants to participate in hacktoberfest!)

**Comment by shiffman** [comment]
@dipamsen I guess the hacktoberfest credit can't go to the submitter b/c the pull request is not opened by them (even though the commits are assigned to them?)

@kaykay this is such a wonderful project, I'm thrilled we are finally getting it on the website!

**Comment by dipamsen** [comment]
> @dipamsen I guess the hacktoberfest credit can't go to the submitter b/c the pull request is not opened by them (even though the commits are assigned to them?)

Yes, the hacktoberfest website only lists the prs from the registered GitHub account.

**Pull request merged**
