### PR TITLE
Update NOC track

### PR DESCRIPTION
**Pull request by kfahn22**
Add simple pendulum and spring forces to NOC track

### CODE REVIEW

**Comment by shiffman** [comment]
Strange, I'm not seeing the videos appear in the deploy preview! https://deploy-preview-940--codingtrain.netlify.app/tracks/the-nature-of-code-2

I wonder if we are missing something or if this is a case of needing a force "clear gatsby cache"?

**Comment by kfahn22** [comment]
I deployed locally before doing the pull request and I saw them. I don't know??

**Comment by shiffman** [comment]
Strange! I'll merge and see if it shows on the site. If not I'll do a clear cache and build.

**Comment by fturmel** [comment]
It's the first time a challenge video is references in a main track as far as I can see, so I might've been a bug, but if @kfahn22 confirms that they showed up locally it must be a new Gatsby cache problem.

It seems to get the new video count right (37), but they don't show up in the track listing.

Screenshot 2023-02-18 at 8 37 10 AM

**Comment by shiffman** [comment]
I can confirm the videos do not appear after merge, I just tried a "clear cache and deploy site" waiting to see what happens!

**Pull request merged**
