### PR TITLE
Add sound classifier video to ml5 track.

### PR DESCRIPTION
**Pull request by kfahn22**
I have also  added the 147-chrome dinosaur challenge to the track.

### CODE REVIEW

**Comment by shiffman** [comment]
@kfahn22 i'm not sure if this makes sense but I moved doodlenet to the image classification section. What do you think?

**Comment by kfahn22** [comment]
That makes sense-it was a single video by itself.  BTW, I was thinking of adding 158-shape classifier to the track and tried the sketches, butI couldn't get them to load in Safari.  I did try on Google chrome and worked as expected.  Maybe it is just me?   (The doodlenet sketches work for me in Safari.)

**Comment by dipamsen** [comment]
Wondering if "ml5.js: " in the video titles are redundant?

image

**Comment by shiffman** [comment]
> That makes sense-it was a single video by itself. BTW, I was thinking of adding 158-shape classifier to the track and tried the sketches, butI couldn't get them to load in Safari. I did try on Google chrome and worked as expected. Maybe it is just me? (The doodlenet sketches work for me in Safari.)

My guess is that you have WEBGL disabled in safari? It's working for me in safari. Although that's odd if doodlenet is fine?

**Comment by shiffman** [comment]
> Wondering if "ml5.js: " in the video titles are redundant?
> 

Yeah, this is a good point. The titles pull from YouTube and it's helpful to have it in there for SEO. But I could move it to the end or I'm open to a way to override titles on the website if we want?

Train your own Neural Network with ml5.js

**Comment by kfahn22** [comment]
I have a lot of sketches using WEBGL, so I don't think that is it.  It is possible it is something to do with my laptop, though.

**Comment by dipamsen** [comment]
> > Wondering if "ml5.js: " in the video titles are redundant?
> 
> Yeah, this is a good point. The titles pull from YouTube and it's helpful to have it in there for SEO. But I could move it to the end or I'm open to a way to override titles on the website if we want?
> 
> Train your own Neural Network with ml5.js

Website titles are totally independent from youtube titles, so it should be fine, right? I think  on the website, there is enough context to the viewer that the video is using ml5.js, unlike youtube where it can be randomly recommended to them.

**Comment by shiffman** [comment]
> Website titles are totally independent from youtube titles, so it should be fine, right? I think on the website, there is enough context to the viewer that the video is using ml5.js, unlike youtube where it can be randomly recommended to them.

Oh, you are right, I was confused! Yes, let's remove ml5 from them for sure, it's redundant! Also, it looks nicer when the titles fit on one line so might be worth keeping that in mind when shortening. Feel free to open a new branch to work on this if you like!

**Comment by kfahn22** [comment]
I have MacOS 13.3 and Safari 16.4, so that is consistent.

**Comment by dipamsen** [comment]
> I agree the ml5 is unnecessary.  Fixing depends on how much effort it would take-- I would love to know a simple approach!  Sorry to ask if this is obvious, but how is the SEO done for the website--I don't see a SEO file in components.

I think just remove the initial ml5.js in the titles of these videos (in `index.json`). The SEO for website should be good, since the video pages themselves do have a title of the track ml5.js (and i believe the same is true for the meta tags for SEO) so it is not required in the video title.

**Comment by kfahn22** [comment]
I was actually wondering if there was a more efficient approach to removing the "ml5.js".

**Comment by dipamsen** [comment]
@kfahn22 Probably a quick find and replace on the ml5 folder would work

**Comment by dipamsen** [comment]
To answer your question on seo, the SEO stuff is actually set in `components/Head.js` - the actual content is derived from the content of the page, eg. The `title` will be title of the challenge/track/video on that page, etc.

**Comment by kfahn22** [comment]
Thanks @dipamsen!

**Comment by kfahn22** [comment]
Sorry, I didn't intend to open two pull requests.  Should I close this one?

**Pull request merged**
