### PR TITLE
A rainy day through your window

### PR DESCRIPTION
**Pull request by Drea007**
Another contribution of mine to the #4-Purple rain challenge

### CODE REVIEW

**Comment by shiffman** [comment]
Would you like to include an image thumbnail with this? (Great work!)

**Comment by Drea007** [comment]
Ofc, yes! What do I have to do?
(Thank u 😊).

**Comment by fturmel** [comment]
@Drea007 You can follow a detailed guide here: https://thecodingtrain.com/guides/passenger-showcase-guide

Don't forget to name your files according to the guide too! There are [17 showcases already](https://github.com/CodingTrain/thecodingtrain.com/tree/main/content/videos/challenges/4-purple-rain/showcase) for this challenge, so yours should be `contribution18`.

**Comment by Drea007** [comment]
@fturmel I already followed this guide by creating a json file and merged into the 'main' branch and the making a pull request. I was only asking how to add a new commit to it as an image file.

**Comment by shiffman** [comment]
Now in #922!

**Pull request closed without merging**
